### ISSUE TITLE
blender data export

### ISSUE THREAD

**Issue by mintarasss** [GoranM/bdx#1039]
I try write a game with GoranM/bdx plugin. When i create plate with texture and try export to code I get fatal error.

Traceback (most recent call last): File "C:\Users\Myuser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bdx\ops\exprun.py", line 225, in execute export(self, context, bpy.context.scene.bdx.multi_blend_export, bpy.context.scene.bdx.diff_export) File "C:\Users\Myuser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bdx\ops\exprun.py", line 123, in export bpy.ops.export_scene.bdx(filepath=file_path, scene_name=scene.name, exprun=True) File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in call ret = op_call(self.idname_py(), None, kw) RuntimeError: Error: Traceback (most recent call last): File "C:\Users\Myuser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bdx\exporter.py", line 903, in execute return export(context, self.filepath, self.scene_name, self.exprun, self.apply_modifier) File "C:\Users\Myuser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bdx\exporter.py", line 829, in export "models": srl_models(objects, apply_modifier), File "C:\Users\Myuser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bdx\exporter.py", line 117, in srl_models verts = vertices(mesh) File "C:\Users\Myuser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bdx\exporter.py", line 53, in vertices vert_uv = list(uv_layer[li].uv) IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189

location: :-1

Maybe someone had same problem and you know how to fix it?

**Comment by rafcolson** [comment]
Not sure what's going on here.

But BDX should export all mesh data. If a mesh does not have a UV layer, it automatically creates one. So my guess is that there's a mesh with an invalid uv layer somehow. So all you do is create a plane, add a material and add a texture and press P?

Maybe try the [latest unofficial BDX version](https://www.dropbox.com/s/qm0i8w9uo1kgvvv/bdx.zip?dl=0).

**Comment by mintarasss** [comment]
@rafcolson Hi, yes I create a plate and add image texture. I do create and add texture like in this video www.youtube.com/watch?v=il7ajiCepus

**Comment by rafcolson** [comment]
Did you start from the default scene (with Sacky) ?

**Comment by mintarasss** [comment]
@rafcolson I have default scene (with Sacky), but I work in other scene, is that a problem?

**Comment by rafcolson** [comment]
No, that shouldn't be a problem. But could you create a new project and just try exporting the default scene?

**Comment by mintarasss** [comment]
@rafcolson I'm so  sorry... it was my mistake, i create a new bdx project  and then noticed that I don’t unfocused object before export. Sorry again.

**Comment by rafcolson** [comment]
No problem at all @mintarasss. Enjoy BDX!
