### ISSUE TITLE
Zip Header not found

### ISSUE THREAD

**Issue by stamoksa** [GoranM/bdx#1048]
Hello,
I've just installed new windows then reinstalled blender ,bdx and jdk 8 
when I start the game it doesn't open and show me error : 
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipExceptio
n: zip END header not found
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAcc
essManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:47)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Sour
ce)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at org.gradle.wrapper.Install.unzip(Install.java:160)
        at org.gradle.wrapper.Install.access$400(Install.java:29)
        at org.gradle.wrapper.Install$1.call(Install.java:70)
        at org.gradle.wrapper.Install$1.call(Install.java:47)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAcc
essManager.java:65)
        ... 3 more
even i installed jdk 10 it shows the same error.

**Comment by GoranM** [comment]
It's been years since I touched BDX source code, and I have no plans to develop or support it further.

BDX is a dead project at this point, so if you really want to use it, you'll probably need to resolve whatever problems you encounter on your own.

**Comment by BluePrintRandom** [comment]
what happened?

**Comment by rafcolson** [comment]
Maybe try jdk-7u79. You can find it here:

https://www.dropbox.com/sh/oqvr4ihta71l6ai/AABhMhvO7j89IRV4jX8ue0Oda?dl=0

**Comment by rafcolson** [comment]
>what happened?

Nothing much. There aren't that many users, or so it seems.

**Comment by stamoksa** [comment]
@GoranM Well thanks for this engine it really helped me 
@rafcolson unfortunately the download link isn't working well and yeah when i try to run it for the first time even i reinstalled blender , bdx and JDK

**Comment by rafcolson** [comment]
@stamoksa Could you tell me what the problem is exactly? You should be getting a DropBox page with four folders. There's no need to install DropBox. You can just explore the folders and download the files you need.

**Comment by BluePrintRandom** [comment]
![image](https://user-images.githubusercontent.com/7190873/47625304-89d90c80-dae1-11e8-971a-d3a6132e21b4.png)
I confirm that dropbox works fine

**Comment by stamoksa** [comment]
![capture](https://user-images.githubusercontent.com/19559739/47680800-99834e80-dbd0-11e8-8004-5e514c2fa18a.PNG)
it shows me this messege on the top "There was an error downloading your file."

**Comment by rafcolson** [comment]
That's strange. I'm not sure what could be the cause of this because I can successfully download the file on my end. But in any case I've added a zipped file to the prerequisites folder. Hopefully that will work.

PS: If you reinstalled your system with a previous build of Windows 10 it is possible that some of the system parts are not working correctly due to the Windows Update process. This can cause some unexpected behavior of the system. I experienced this many times before, especially when updates are being installed or have been installed without the system being restarted. So make sure that everything is up-to-date first. I'm mentioning this just in case.

**Comment by BluePrintRandom** [comment]
It could be local setting blocking this type of transfer also

**Comment by stamoksa** [comment]
Unfortunately it still show me that error even i turned off my firewall perhaps it be the cause of this error .
actually i downgraded me Win 10 to 7

**Comment by rafcolson** [comment]
>actually i downgraded me Win 10 to 7

Maybe try to dowload with another pc or you could also try to download jdk-7u80 from another source.

**Comment by stamoksa** [comment]
ok thanks for helping bro will try

**Comment by stamoksa** [comment]
Sorry for replying late was in exams ,
i downloaded it using vpn but unfortunately that didn't fix the blender error 
any other suggestions?

**Comment by stamoksa** [comment]
Now managed to fix it by deleting .gradle file in (C:\Users\Users\.gradle)
and let the program build it by itself even it shows other errors not realated to it but at least this error has gone
thanks for helping.

**Comment by rafcolson** [comment]
Glad it worked out. But I wonder.. after deleting it, were dependencies being downloaded on first run?

**Comment by stamoksa** [comment]
Yeah it does

**Comment by rafcolson** [comment]
Thanks.

**Comment by stamoksa** [comment]
Thank you.
Shall i close this issue?

**Comment by rafcolson** [comment]
Yes.

**Comment by stamoksa** [comment]
Ok thanks for helping
