### ISSUE TITLE
Bug: Gradle dependencies unavailable on install (previously they where)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1050]
I've been trying to install BDX but without success.

My setup had worked before:
- jdk-7u79-windows-x64.exe
- apache-ant-1.9.14-bin.zip
- sdk-tools-windows-installer_r24.4.1-windows.exe

Has anyone else experienced this problem with a fresh install of BDX? It seems as if these Gradle dependencies don't even exist anymore. Hopefully I'm just doing something wrong here.

```java
Read prefs: C:\Users\Raf\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Builds\2.79c\Blender\2.79\python
Read blend: F:\Coding\BDX\Projects\Test\test-creator.blend
Extension controllers found
Extension tools found
Executing 'F:\Coding\BDX\Projects\Test\Test/gradlew.bat clean'
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Test'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve de.richsource.gradle.plugins:gwt-gradle-plugin:0.6.
     Required by:
         :Test:unspecified
      > Could not resolve de.richsource.gradle.plugins:gwt-gradle-plugin:0.6.
         > Could not get resource 'https://repo1.maven.org/maven2/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.pom'.
               > peer not authenticated
      > Could not resolve de.richsource.gradle.plugins:gwt-gradle-plugin:0.6.
         > Could not get resource 'https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.pom'.
            > Could not GET 'https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.pom'.
               > peer not authenticated
   > Could not resolve com.android.tools.build:gradle:1.5.0.
     Required by:
         :Test:unspecified
      > Could not resolve com.android.tools.build:gradle:1.5.0.
         > Could not get resource 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'.
               > peer not authenticated
      > Could not resolve com.android.tools.build:gradle:1.5.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'.
               > peer not authenticated
   > Could not resolve org.robovm:robovm-gradle-plugin:1.12.0.
     Required by:
         :Test:unspecified
      > Could not resolve org.robovm:robovm-gradle-plugin:1.12.0.
         > Could not get resource 'https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.12.0/robovm-gradle-plugin-1.12.0.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.12.0/robovm-gradle-plugin-1.12.0.pom'.
               > peer not authenticated
      > Could not resolve org.robovm:robovm-gradle-plugin:1.12.0.
         > Could not get resource 'https://jcenter.bintray.com/org/robovm/robovm-gradle-plugin/1.12.0/robovm-gradle-plugin-1.12.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/robovm/robovm-gradle-plugin/1.12.0/robovm-gradle-plugin-1.12.0.pom'.
               > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.306 secs
Read blend: F:\Coding\BDX\Projects\Test\Test\blender\game.blend

```

**Comment by SolarLune** [comment]
Yo. Yeah, I believe I also ran into similar issues as well a couple of weeks ago; I eventually got it to work, but had to mess around with it a bit.

**Comment by rafcolson** [comment]
Hi there @SolarLune. Hope you're fine. I'll look into it some more but if you have any idea about what the solution might be I'm happy to hear from you.

**Comment by rafcolson** [comment]
@SolarLune 
Can you perhaps tell me how you got it to work? I'm struggling...

**Comment by SolarLune** [comment]
I'm able to get past this particular step, but I still can't create and run a new project. To get to where I am now, I think I tried destroying the .gradle folder and re-downloading all of the assets. I think I tried deleting the .gradle folder and redownloading everything after exporting again. Still got stuck on actual launch with an error on attempting to create a model, though.

I believe I might have also tried messing with the gradle settings for the project, but I don't think that's necessary for a new project.

**Comment by rafcolson** [comment]
Thanks.

What I did was replacing my _.gradle_ directory entirely with the one I had on my other laptop. The project is created successfully but get errors running the game, related to the java version. It speaks for itself that there should be a fix so it would still be possible to export your game for android (which requires Java versions prior to 8).

```java
Read prefs: C:\Users\Raf\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Builds\2.79c\Blender\2.79\python
Read blend: F:\Coding\BDX\Projects\Test\test-creator.blend
Extension controllers found
Extension tools found
Executing 'F:\Coding\BDX\Projects\Test\Test/gradlew.bat clean'
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.
:android:clean UP-TO-DATE
:core:clean UP-TO-DATE
:desktop:clean UP-TO-DATE
:html:clean UP-TO-DATE
:ios:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1 mins 22.805 secs
Read blend: F:\Coding\BDX\Projects\Test\Test\blender\game.blend
BDX - Export Finished

------------ BDX START --------------------------------------------------

Configuration on demand is an incubating feature.
:core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
warning: F:\Coding\BDX\Projects\Test\Test\core\libs\bdx.jar(com/nilunder/bdx/GameObject.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: F:\Coding\BDX\Projects\Test\Test\core\libs\bdx.jar(com/nilunder/bdx/Bdx.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: F:\Coding\BDX\Projects\Test\Test\core\libs\bdx.jar(com/nilunder/bdx/Scene.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: F:\Coding\BDX\Projects\Test\Test\core\libs\bdx.jar(com/nilunder/bdx/Bdx$ArrayListScenes.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: F:\Coding\BDX\Projects\Test\Test\core\libs\bdx.jar(com/nilunder/bdx/utils/ArrayListNamed.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
6 warnings
:core:processResources UP-TO-DATE
:core:classes
:core:jar
:desktop:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:desktop:processResources UP-TO-DATE
:desktop:classes
:desktop:run
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsupportedClassVersionError: com/nilunder/bdx/Bdx : Unsupported major.minor version 52.0
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.UnsupportedClassVersionError: com/nilunder/bdx/Bdx : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.raco.test.BdxApp.create(BdxApp.java:15)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

BUILD SUCCESSFUL

Total time: 11.569 secs

------------ BDX END ----------------------------------------------------
```

I'm not really sure what is going on but it seems that some dependencies are moved so the gradle version is unable to find those. Do you know if updating to a more recent version of LibGdx would make sure that also an updated gradle version is used?

**Comment by vittfiles** [comment]
Did you manage to implement jdk 8?

**Comment by rafcolson** [comment]
> Did you manage to implement jdk 8?
I didn't try to do this because I wasn't sure if this could solve the issue.

**Comment by vittfiles** [comment]
I think that for gradle to download you need java 8 as a minimum, so install it.
I created a project in bdx and when exporting it there was an error searching for the jar.
so edit the distributionUrl = https \: //services.gradle.org/distributions/gradle-2.8-all.zip in the gradle-wrapper file.
and having android build tool 20 I download well but still blender could not find the jar.
so in build.gradle of the project I change gdxVersion = '1.9.10' and I download everything well but still blender does not find the jar.
it's related to the sources but I don't know why he can't find them because they are where he looks.
Maybe you have to update libgdx in the bdx master itself, but I don't know anything about "ant".

**Comment by rafcolson** [comment]
Maybe @SolarLune could give you some pointers as he uses java8 before. I also don't know much about how to upgrade BDX to a higher version of LibGdx.

**Comment by vittfiles** [comment]
I tried to compile the github BDX-master with ant and it tells me that in Profiles.java the builder is bad and the ones are not defined.
the problem is that I don't know where those variables come from.
[error.txt](https://github.com/GoranM/bdx/files/4189122/error.txt)

**Comment by rafcolson** [comment]
Upgrading to a higher Gdx version probably requires updating the BDX codebase. Several classes may have been altered. You could search the release notes to figure out what has changed related to BDX. Unless this relates to the aforementioned issue. Because I still have no idea what that's all about.

**Comment by vittfiles** [comment]
fix those glprofile errors and compile it with ant.
in blender it creates in project and exports it but when executing it it says error for trying to download moe-sdk.I have no idea why but I am in it.

**Comment by vittfiles** [comment]
I managed to make it work but the first time it takes a long time to create the game because gradle takes a long time to download the ios-moe sdk.
After creating the blender project, you export the scene but cannot execute due to an error in ios-moe.
so you have to delete "ios" and "ios-moe" in the file "sittings.gradle" and "build.gradle".
Then in blender export the scene and run it and it works fine. I don't try it for Android.
[bdx.zip](https://github.com/GoranM/bdx/files/4189446/bdx.zip)

**Comment by rafcolson** [comment]
I could test if exporting for android works. If your branch with the update is even with master I could fork your branch and try to build myself.

**Comment by vittfiles** [comment]
I tested it in Android Studio on a mobile with Android 5.1 and it worked.

**Comment by rafcolson** [comment]
Nice job!

**Comment by vittfiles** [comment]
later I will try not to download that ios-moe project because I am tired.in Argentina it's 0hs

**Comment by rafcolson** [comment]
No hurries.

**Comment by vittfiles** [comment]
It is not so comfortable.
this is the uncompiled project: 
[bdx-master.zip](https://github.com/GoranM/bdx/files/4207716/bdx-master.zip)
this is the compiles bdx: 
[bdx.zip](https://github.com/GoranM/bdx/files/4207718/bdx.zip)
After creating a project (game) it will surely take a long time the first time.
when the project is finished, the project cannot be exported because it does not download the jar and cannot be run because gradle has a problem with ios-moe.
Solution:
1- in the project:
  --in gradle.settings delete "ios-moe".
  --in build.gradle delete everything contained in "ios-moe{".
2-import the project into AndroidStudio or eclipse so that the jar is downloaded.This is only necessary the first time you use bdx.
3-now you can export the scene and run it in blender.

**Comment by vittfiles** [comment]
It's not the best solution but it's what I can do with what I know.
It's a good engine and very simple, that's why I'm interested

**Comment by rafcolson** [comment]
Thanks @vittfiles.

With your source I might be able to sort out how to fix the issue.

A question. Did you make changes to the latest build of bdx or did you use your own master (which is out-dated)?

**Comment by vittfiles** [comment]
use the github project don't download it from the latest version.
Now I will try to do that

**Comment by vittfiles** [comment]
In the bdx-master file that I put in the message above, change the following:
- in build.xml: <property name = "libgdx.version" value = "1.9.10" />
- in Profiler.java: some problems with private variables.
- in createproj.py:
               "--excludeModules", '"ios-moe"',
               "--extensions", "controllers; tools; freetype"]

**Comment by rafcolson** [comment]
Okay. Thanks. I'll make some time this week to take a look at it.

**Comment by vittfiles** [comment]
in python add to delete ios-moe information from build.gradle and settings.
Now after creating the first bdx project in blender you have to run the program so that the jar is installed for the first time. Then you can export the scene normally.
you don't need to import the gradle project in android studio or eclipse to download the jar.
uncompiles:
[https://drive.google.com/file/d/1iw1SUxiZCNdx9dbmaJMcy0EjYi18xFQu/view?usp=sharing](url)
compile for blender:
[https://drive.google.com/file/d/1w_L7UTqnyHCbUFYauprODHeN8Fuejx5H/view?usp=sharing](url)
