### ISSUE TITLE
Mac OSX Yosemite Build Error

### ISSUE THREAD

**Issue by slightfx** [GoranM/bdx#11]
Hi.

Getting this error: when i run ./gradlew :desktop:run

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.nilunder.bdx.GameObject.updateLocalScale(GameObject.java:304)
	at com.nilunder.bdx.GameObject.parent(GameObject.java:83)
	at com.nilunder.bdx.Scene.hookParentChild(Scene.java:220)
	at com.nilunder.bdx.Scene.init(Scene.java:189)
	at com.nilunder.bdx.Scene.<init>(Scene.java:86)
	at com.nilunder.bdx.Scene.<init>(Scene.java:76)
	at com.ssc.test.BdxApp.create(BdxApp.java:32)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:136)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

BUILD SUCCESSFUL

Total time: 5.289 secs

Is there any special JDK version I should use? 
Currently running with: jdk-8u25

**Comment by rafcolson** [comment]
@slightfx Just out of curiosity, are you still having the issue you were describing?

**Comment by tylerpitchford** [comment]
I'm seeing the issue:

./gradlew :desktop:run
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.nilunder.bdx.GameObject.updateLocalScale(GameObject.java:430)
	at com.nilunder.bdx.GameObject.parent(GameObject.java:92)
	at com.nilunder.bdx.Scene.hookParentChild(Scene.java:243)
	at com.nilunder.bdx.Scene.init(Scene.java:212)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:18)
	at com.nilunder.testgame.BdxApp.create(BdxApp.java:35)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:136)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

----
----

java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
Machine:bdx-test-game tpitchford$

**Comment by SolarLune** [comment]
Not quite sure, but here's a couple of guesses / questions:

1) Is this a fresh install of BDX and a fresh project?
2) Do you have other versions of Java on your computer?
3) What OS are you using (guessing Mac, but not sure)?

**Comment by tylerpitchford** [comment]
1. Actually, I was attempting to build: https://github.com/GoranM/bdx-test-game . I cloned it and attempted to compile.

2. Yes, I also have: 1.8.0_05 and 1.8.0_45

3. And, sorry about that, I meant to include the OS. It's Mac OS/X 10.10.3.

Best,
Tyler

**Comment by SolarLune** [comment]
Does BDX work with the template / basic game? 

It would appear that Goran last updated that demo repo several months ago, so I wouldn't be surprised if it doesn't work with BDX anymore.

**Comment by tylerpitchford** [comment]
No, it doesn't. That's actually why I was attempting the demo repo. The
template / basic never appears.

Best,
Tyler

**Comment by SolarLune** [comment]
OK, now that's strange. What happens when you attempt to build a new
project? Doesn't a "game.blend" file get generated when you create a BDX
project?

As a side-note, did you look into what Goran mentioned about removing the
pre-installed version of javax.vecmath, or excluding it from the default
classpath?

As another question, have you installed Java at all manually, or did these
distributions for some reason come with your Mac? Having multiple Java
versions probably isn't the issue, but it is odd to have multiple full
distributions of almost the same versions.

**Comment by slightfx** [comment]
So after a bit of doing something else than blender stuff, I came back to BDX and managed to get it to work, on my mac. 

I think the trick was to delete /System/Library/Java and putting the update vecmath into the CLASSPATH in the gradlew file, but Im not 100% sure :)

But at least I'm done digging for a solution :)

Thx @GoranM & @SolarLune

**Comment by songproducer** [comment]
I'm having the same problem but I don't want to uninstall my system Java and not sure how to change the CLASSPATH in the gradlew file to update vecmath.
