### ISSUE TITLE
Bug: Can't Create BDX Project

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#311]
Hey, there. So in working, I've found that I can't build a new project in BDX. I get the following error:

```
Traceback (most recent call last):                                                 
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.72\scripts\
addons\bdx\ops\createproj.py", line 222, in execute                                
    self.create_libgdx_project()                                                   
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.72\scripts\
addons\bdx\ops\createproj.py", line 43, in create_libgdx_project                   
    subprocess.check_call(cmd)                                                     
  File "C:\tools\Blender\Current Blender\2.72\python\lib\subprocess.py", line 556, 
in check_call                                                                      
    retcode = call(*popenargs, **kwargs)                                           
  File "C:\tools\Blender\Current Blender\2.72\python\lib\subprocess.py", line 537, 
in call                                                                            
    with Popen(*popenargs, **kwargs) as p:                                         
  File "C:\tools\Blender\Current Blender\2.72\python\lib\subprocess.py", line 858, 
in __init__                                                                        
    restore_signals, start_new_session)                                            
  File "C:\tools\Blender\Current Blender\2.72\python\lib\subprocess.py", line 1111,
 in _execute_child                                                                 
    startupinfo)                                                                   
FileNotFoundError: [WinError 2] The system cannot find the file specified          
```

It looks like BDX fills in the Android SDK field (incorrectly) when this happens, so maybe that's some part of the reason why?

I'm using the latest version of a clean BDX build from source.

**Comment by rafcolson** [comment]
@SolarLune I'm having no problems creating a BDX project. [Here](https://github.com/GoranM/bdx/issues/291#issuecomment-100217998) you can see what my configuration is. And I assume you have the same setup.

So I'm suspecting that your problem is caused by your Blender version.

**Comment by SolarLune** [comment]
Thanks for the tip, that helped. I didn't actually install everything from scratch; using the latest version of Blender seems to have fixed it.
