### ISSUE TITLE
Bug: Can't Enable Framerate and Profiler

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#366]
Hey, there. So, enabling the Framerate and Profiler on my current WIP project and exporting and running gives me an error:

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.nilunder.bdx.Scene.init(Scene.java:219)
        at com.nilunder.bdx.utils.Profiler.show(Profiler.java:67)
        at com.nilunder.bdx.utils.Profiler.init(Profiler.java:55)
        at com.nilunder.bdx.Scene.init(Scene.java:139)
        at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:50)
        at com.solarlune.nmsgamejam.BdxApp.create(BdxApp.java:18)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

It works otherwise (only with the code I submitted (#365)). However, on a fresh, newly made project, though, I get a different result. If I don't have Framerate and Profile on, it all runs fine. With it on, though, The `__Profiler` scene gets copied into the blend file (unlike my WIP project blend file), and I get a different error:

```
Traceback (most recent call last):                                                 
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\
addons\bdx\ops\exprun.py", line 52, in execute                                     
    bpy.ops.export_scene.bdx(filepath=file_path, scene_name=scene.name, exprun=True
)                                                                                  
  File "C:\tools\Blender\Current Blender\2.74\scripts\modules\bpy\ops.py", line 189
, in __call__                                                                      
    ret = op_call(self.idname_py(), None, kw)                                      
RuntimeError: Error: Traceback (most recent call last):                            
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\
addons\bdx\exporter.py", line 732, in execute                                      
    return export(context, self.filepath, self.scene_name, self.exprun)            
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\
addons\bdx\exporter.py", line 672, in export                                       
    "dimensions": srl_dimensions(objects),                                         
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\
addons\bdx\exporter.py", line 144, in srl_dimensions                               
    data_name = "__FNT_" + o.data.name if o.type == "FONT" else o.data.name        
AttributeError: 'NoneType' object has no attribute 'name'                          
                                                                                   
location: C:\tools\Blender\Current Blender\2.74\scripts\modules\bpy\ops.py:189     
```

**Comment by rafcolson** [comment]
PR submitted.

**Comment by SolarLune** [comment]
@rafcolson 's PR has been submitted and merged, and I think it fixed this issue. So, I'll close it. Thanks!
