### ISSUE TITLE
Export and run on old version of bdx causes crash

### ISSUE THREAD

**Issue by billy1380** [GoranM/bdx#383]
This seems to be due to some missing attribues in a json file that causes Scene.java to throw all kinds of null reference exceptions. Is there a way to test for the version of the file and regenerate it.

**Comment by GoranM** [comment]
You have to re-create the project, as described here: https://github.com/GoranM/bdx/wiki#updating-bdx

**Comment by billy1380** [comment]
Cool... totally missed that :anguished: closing...

**Comment by billy1380** [comment]
BTW... still cannot get a freshly created bdx project to run on html:superdev without crashing... where as using libgdx directly works fine any thoughts?

**Comment by GoranM** [comment]
We need more information.

Make an issue called "HTML build problems", and post the actual error that you're getting (I assume there's an error of some sort).

Also, be sure to explain your testing process. I assume you:

* build BDX from source
* open a new blender instance
* install the freshly built BDX addon
* create a new BDX project
* run html:superdev

PS: You should first close #379 and #380, because your patches for those issues have been merged.

**Comment by billy1380** [comment]
I did... fresh install of BDX, fresh project. Will post full details in a new bug tomorrow. Also, closed #379 and #380. Thanks.

**Comment by billy1380** [comment]
I have followed the instructions but the project crashes on Cloud.java because it cannot find parents.

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.nilunder.testgame.Cloud.init(Cloud.java:25)
	at com.nilunder.bdx.Scene.initGameObject(Scene.java:394)
	at com.nilunder.bdx.Scene.init(Scene.java:269)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:56)
	at com.nilunder.testgame.Player.init(Player.java:25)
	at com.nilunder.bdx.Scene.initGameObject(Scene.java:394)
	at com.nilunder.bdx.Scene.initGameObject(Scene.java:399)
	at com.nilunder.bdx.Scene.init(Scene.java:269)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:50)
	at com.nilunder.testgame.BdxApp.create(BdxApp.java:20)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

Has something changed in the way groups are treated?

**Comment by GoranM** [comment]
This doesn't seem to be related to the original problem, so you should make a new issue.

It would help if you could tell us where you are, currently, in the tutorial series.

**Comment by billy1380** [comment]
Will do... will put some more details in the new issue.
