### ISSUE TITLE
Can I use BDX with Scala?

### ISSUE THREAD

**Issue by KonstantTom** [GoranM/bdx#431]
Hi! Can I use BDX with Scala? 

I create basic BDX project in blender. Project successfully works on android emulator.

I use this tutorial to add scala support to project:

[**Using libGDX and Scala with Gradle**](https://github.com/libgdx/libgdx/wiki/Using-libgdx-with-Scala#using-libgdx-and-scala-with-gradle)

When I do it, desktop project works successfully, but android project does not start. :(
Android project stacktrace:
```
08-31 17:02:36.217: E/AndroidRuntime(12453): FATAL EXCEPTION: GLThread 237
08-31 17:02:36.217: E/AndroidRuntime(12453): Process: com.ekit.bdxandroidtest.android, PID: 12453
08-31 17:02:36.217: E/AndroidRuntime(12453): com.badlogic.gdx.utils.i: Error creating controller manager: com.badlogic.gdx.controllers.android.AndroidControllers
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at com.badlogic.gdx.c.e.a(Unknown Source)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at com.b.a.c.b.<init>(Unknown Source)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at com.b.a.a.a(Unknown Source)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at com.ekit.bdxandroidtest.a.a(Unknown Source)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at com.badlogic.gdx.backends.android.h.onSurfaceChanged(Unknown Source)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-31 17:02:36.217: E/AndroidRuntime(12453): Caused by: com.badlogic.gdx.utils.b.b: Class not found: com.badlogic.gdx.controllers.android.AndroidControllers
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at com.badlogic.gdx.utils.b.a.a(Unknown Source)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	... 7 more
08-31 17:02:36.217: E/AndroidRuntime(12453): Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.controllers.android.AndroidControllers
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at java.lang.Class.classForName(Native Method)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at java.lang.Class.forName(Class.java:251)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at java.lang.Class.forName(Class.java:216)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	... 8 more
08-31 17:02:36.217: E/AndroidRuntime(12453): Caused by: java.lang.NoClassDefFoundError: com/badlogic/gdx/controllers/android/AndroidControllers
08-31 17:02:36.217: E/AndroidRuntime(12453): 	... 11 more
08-31 17:02:36.217: E/AndroidRuntime(12453): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.badlogic.gdx.controllers.android.AndroidControllers" on path: DexPathList[[zip file "/data/app/com.ekit.bdxandroidtest.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ekit.bdxandroidtest.android-1, /system/lib, /system/lib/arm, /data/downloads]]
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
08-31 17:02:36.217: E/AndroidRuntime(12453): 	... 11 more
```

Sorry for proguard code obfuscation, but without proguard I can't build android project(after scala support):
```
Unable to execute dex: method ID not in [0, 0xffff]: 65536
```

**UPD.** I think Proguard erases or renames class ***com.badlogic.gdx.controllers.android.AndroidControllers***, but how i can stop it?

**Comment by GoranM** [comment]
Looking at your stack trace, it seems like you're missing the AndroidControllers class, so that's something you should research.

I don't really know anything about Scala in libgdx. I only focused on Java, because that's the only language that GWT can transpile to JavaScript - If you write your game in any other language, you won't be able to create an HTML5 build.

**Comment by KonstantTom** [comment]
>UPD. I think Proguard erases or renames class com.badlogic.gdx.controllers.android.AndroidControllers, but how i can stop it?

What do you think about this? If I disable proguard and scala -- android build works successfully. But i can't disable Proguard, because scala support don't works without Proguard.

**Comment by KonstantTom** [comment]
To solve this problem I add to proguard-project.txt this lines:
```
-keep class com.badlogic.gdx.controllers.android.AndroidControllers
```
All works successfully. :)
