### ISSUE TITLE
Bug: Scene Restart Doesn't End GameObjects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#442]
Hey, there. So basically, if you restart a game scene, the game objects within aren't ended, and so their references never turn invalid.

I'm looking into fixing this now, but it seems like it might not be possible under our current code-base. I tried just adding a loop to end all objects in the scene, but I can't because we can't simply dispose of models or textures twice, and I don't see a way to check to see if a model's been disposed already. This is the error I get:

```
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: buffer not allocated with newUnsafeByteBuffer or already disposed
        at com.badlogic.gdx.utils.BufferUtils.disposeUnsafeByteBuffer(BufferUtils.java:507)
        at com.badlogic.gdx.graphics.glutils.VertexBufferObject.dispose(VertexBufferObject.java:219)
        at com.badlogic.gdx.graphics.Mesh.dispose(Mesh.java:581)
        at com.badlogic.gdx.graphics.g3d.Model.dispose(Model.java:350)
        at com.nilunder.bdx.GameObject.endNoChildren(GameObject.java:556)
        at com.nilunder.bdx.GameObject.end(GameObject.java:548)
        at com.nilunder.bdx.Scene.runObjectLogic(Scene.java:666)
        at com.nilunder.bdx.Scene.update(Scene.java:718)
        at com.nilunder.bdx.Bdx.main(Bdx.java:178)
        at com.solarlune.airgrift.BdxApp.render(BdxApp.java:29)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:214)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

I guess an alternative would be to simply end the current scene and start a new duplicate scene at the same position when scene.restart() is called? References to the scene would be wrecked, of course, which is kind of a similar problem as what it is currently.

EDIT: Another alternative would be to make a "secret" undocumented function that simply allows BDX to force the validity on GameObjects.

**Comment by GoranM** [comment]
> I tried just adding a loop to end all objects in the scene, but I can't because we can't simply dispose of models or textures twice, and I don't see a way to check to see if a model's been disposed already.

It seems like the end method is being called multiple times for the same object. That's the core problem.

If you're doing this:

```java
for (GameObject o : objects){
    o.end();
}
```

You're ending all the children as well, but the children are still in the list, so you'll call end on them again, and that will throw the exception.

This would probably work fine:

```java
for (GameObject o : objects){
    o.endNoChildren();
}
````

If it does, it would confirm my assumptions about the problem, and we can then add the following at the beginning of `endNoChildren()`:

```java
if (!valid)
    return;
```

**Comment by SolarLune** [comment]
PR submitted. Worked first try - thanks for the help!

**Comment by SolarLune** [comment]
Cool, this was merged. I'll close it now. Thanks!
