### ISSUE TITLE
Can't Convert Font Under Certain Circumstances

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#463]
Hey, there. So basically, if you try to use some (most?) fonts with BDX, it'll crash due to a unicode error. Looking around online, it looks like we need to use a raw string or double-stack our forward slashes?

```SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \URuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\bdx\exporter.py", line 827, in execute
    return export(context, self.filepath, self.scene_name, self.exprun)
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\bdx\exporter.py", line 783, in export
    generate_bitmap_fonts(fonts, hiero_dir, fonts_dir, textures_dir);
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\bdx\exporter.py", line 725, in generate_bitmap_fonts
    json.dump(ut.angel_code(fnt), f)
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\bdx\utils.py", line 133, in angel_code
    (key, _), *data = line_to_items(l)
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\bdx\utils.py", line 128, in line_to_items
    return [(k, eval(v)) for k, v in items]
  File "C:\Users\SolarLune\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\bdx\utils.py", line 128, in <listcomp>
    return [(k, eval(v)) for k, v in items]
  File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape```

I'm not sure, but it could be an issue I'm facing locally because of my setup or something? The project's located in my user directory Has anyone else had any issues converting fonts in BDX recently? If not, it might be due to another font-related program that I installed on my computer recently... I'll have to see - it seems like it might be moving the file and then converting it in my Pictures directory. If that's the case, then one of the strings might be "C:/Users...", which might be part of the problem...? I'm not sure currently, I never had issues converting fonts before, so this might be an isolated incident only related to me. I'll check in a few with a system restart.

**Comment by SolarLune** [comment]
OK, looks like it might have been due to another program that I installed that converts fonts - namely Shoebox. Uninstalling it and creating a new project (which ran gradle.bat clean) seemed to fix it, and for multiple projects, both a new one and a pre-existing one. I'm going to assume that Shoebox installs some existing font conversion software that BDX / LibGDX was also pointing to, and that's what caused the hubbub. 

Issue solved and closed!
