### ISSUE TITLE
BUG:Can't run the desktop demo

### ISSUE THREAD

**Issue by xirtam-ch** [GoranM/bdx#510]
Controllers: added manager for application, 1 managers active
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:130)
Caused by: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.nilunder.bdx.GameObject.updateLocalScale(GameObject.java:621)
	at com.nilunder.bdx.GameObject.parent(GameObject.java:147)
	at com.nilunder.bdx.GameObject.parent(GameObject.java:118)
	at com.nilunder.bdx.Scene.hookParentChild(Scene.java:347)
	at com.nilunder.bdx.Scene.init(Scene.java:301)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:51)
	at com.xirtam.test11.BdxApp.create(BdxApp.java:18)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:146)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)

Process finished with exit code 0

**Comment by xirtam-ch** [comment]
same with https://github.com/GoranM/bdx/issues/11
