### ISSUE TITLE
Bug: Restart Crashes Because of ShapeRenderer

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#531]
Hey, there. Disposing the scene's ShapeRenderer, added with the last drawLine and drawPoint functions, crashes BDX. The error is:

```java
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: buffer not allocated with newUnsafeByteBuffer or already disposed
        at com.badlogic.gdx.utils.BufferUtils.disposeUnsafeByteBuffer(BufferUtils.java:507)
        at com.badlogic.gdx.graphics.glutils.VertexBufferObject.dispose(VertexBufferObject.java:260)
        at com.badlogic.gdx.graphics.Mesh.dispose(Mesh.java:507)
        at com.badlogic.gdx.graphics.glutils.ImmediateModeRenderer20.dispose(ImmediateModeRenderer20.java:174)
        at com.badlogic.gdx.graphics.glutils.ShapeRenderer.dispose(ShapeRenderer.java:1129)
        at com.nilunder.bdx.utils.Bullet$DebugDrawer.dispose(Bullet.java:80)
        at com.nilunder.bdx.Scene.dispose(Scene.java:346)
        at com.nilunder.bdx.Scene.end(Scene.java:845)
        at com.nilunder.bdx.Bdx.restart(Bdx.java:353)
...
```

Being that this appears to be an internal thing, the solution I'm proposing is to make the ShapeRenderer static, so there's only one created and only one that all scenes use. Then we don't really need to dispose of it, since the only time it'd be destroyed is if the game ends.

Submitting PR.

**Comment by SolarLune** [comment]
PR merged. Closing this!
