### ISSUE TITLE
Pressing an Unknown Key Crashes BDX

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#55]
Hey, there. So, it would appear that if you press a key that is unknown to BDX (e.g. Print Screen or NumLock), it will crash the engine. Here's the error
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.nilunder.bdx.inputs.GdxProcessor.keyDown(GdxProcessor.java:21)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:300)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:199)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
```

**Comment by GoranM** [comment]
:smile:

**Comment by SolarLune** [comment]
Hah, thanks a lot!

... Now I need to fix it. :|

**Comment by GoranM** [comment]
The codeToLog hash doesn't have anything for keys that are not defined on Keyboard, so `keyboard.codeToLog.get(code)` will return null when GDX provides a code we don't handle. Trying to reference `k.hit`, in that case, will cause a NullPointerException.

You just need a clause to avoid that exception, and that should solve the problem.

Although, if you don't feel like doing it, that's no problem - just let me know.

**Comment by SolarLune** [comment]
Thanks for the tip - I've got a patch up for merging (#58).

**Comment by SolarLune** [comment]
Committed.
