### ISSUE TITLE
BDX Crashes with Ghost Static Object

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#60]
Hey, there. So yeah, if an object is static and has "Ghost" ticked, under a specific condition (I can't seem to figure out exactly what it is), BDX will crash on start. I've attached a test blend file that demonstrates the issue.

https://app.box.com/s/sxpt97col246jufsy81c

**Comment by GoranM** [comment]
It seems to happen when static objects, set to ghost, with triangle mesh bounds, come into contact.

This seems to be a bug in jbullet, so I don't think there's much I can do about it, other than disabling triangle mesh bounds for static objects set to ghost (defaulting to box instead) ... I don't know.

I'll first have to confirm that it is indeed a jbullet issue, rather than anything to do with how I'm setting up the bullet world (this may take a while).

For now, it seems like you could just use Box bounds (instead of triangle mesh, which is the default for static objects), and that would work fine.

**Comment by SolarLune** [comment]
Hm, I see. Seems like Convex Hull would get pretty close to the actual shape of the object for some cases, though I could see it still being an issue for people that aren't aware of the bug, so maybe it shouldn't change "under the hood". Maybe you could print out a message to the console to this effect?

`Static ghost triangle mesh >mesh_name< not supported. Changed >object_name< to convex hull collision type!` 

It would seem this issue should remain open so future users will know about it (or until it's fixed, if possible).

**Comment by GoranM** [comment]
I think we could just catch that particular exception when raised, and then print why it happened:

```Detected collision between Static objects set to Ghost, with Triangle Mesh bounds: Keep them separated, or use different bounds.```

And yea, we should keep this issue open for now.

**Comment by SolarLune** [comment]
Looks like this also causes a crash if the Static Ghost object is ended(). Console lists:

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.bulletphysics.collision.dispatch.CollisionDispatcher.freeCollisionAlgorithm(CollisionDispatcher.java:126)
        at com.bulletphysics.collision.broadphase.HashedOverlappingPairCache.cleanOverlappingPair(HashedOverlappingPairCache.java:225)
        at com.bulletphysics.collision.broadphase.HashedOverlappingPairCache$CleanPairCallback.processOverlap(HashedOverlappingPairCache.java:453)
        at com.bulletphysics.collision.broadphase.HashedOverlappingPairCache.processAllOverlappingPairs(HashedOverlappingPairCache.java:196)
        at com.bulletphysics.collision.broadphase.HashedOverlappingPairCache.cleanProxyFromPairs(HashedOverlappingPairCache.java:213)
        at com.bulletphysics.collision.dispatch.CollisionWorld.removeCollisionObject(CollisionWorld.java:175)
        at com.bulletphysics.dynamics.DiscreteDynamicsWorld.removeRigidBody(DiscreteDynamicsWorld.java:435)
        at com.nilunder.bdx.Scene.remove(Scene.java:374)
        at com.nilunder.bdx.GameObject.endNoChildren(GameObject.java:339)
        at com.nilunder.bdx.GameObject.end(GameObject.java:331)
        at com.nilunder.bdx.GameObject.end(GameObject.java:329)
        at com.solarlune.kyro.objects.TeleportGem.die(TeleportGem.java:97)
        at com.solarlune.kyro.objects.Player.main(Player.java:125)
        at com.nilunder.bdx.Scene.runObjectLogic(Scene.java:556)
        at com.nilunder.bdx.Scene.update(Scene.java:610)
        at com.solarlune.kyro.BdxApp.render(BdxApp.java:59)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:206)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
```

**Comment by GoranM** [comment]
I can't reproduce.

I'm setting the default Platform to ghost, and then in Platform.java I call end() when I hit space.

Platform is removed without error.

The best way to confirm these things is to actually isolate the issue in a small example, rather than just assume from behavior you see in your game (also, if the other person can't reproduce, you have something to share).

**Comment by SolarLune** [comment]
> The best way to confirm these things is to actually isolate the issue in a small example, rather than just assume from behavior you see in your game (also, if the other person can't reproduce, you have something to share).

I'm aware of that. I assumed this was an additional "static ghost object" quirk, considering this one exists already. You're right that I should have a small example to show the issue (I usually do). 

I don't intend to spend time on isolating this; I commented just to keep a record in case it's related. I'm going to just assume it's part of the same underlying "static ghost" issue until I can come up with some more info.

**Comment by GoranM** [comment]
> I don't intend to spend time on isolating this; I commented just to keep a record in case it's related.

Wouldn't it be more sensible to simply wait until you can confirm things in some respect, or have some supporting data?

I mean, I'm not sure if it's a good idea to use issues as a personal notebook - it should be a record of refined information, derived from data, which can actually be used to solve the problem at hand.

**Comment by GoranM** [comment]
I don't really want to muck around with gbullet internals, so rather than trying to hack around this bug on the inside, I decided to simply throw a more informative exception.

**Comment by SolarLune** [comment]
Sounds like a good idea. Thanks! Should I close this issue?

**Comment by GoranM** [comment]
I guess it would be ok to close at this point. Yea.
