### ISSUE TITLE
Issue with scene creating

### ISSUE THREAD

**Issue by OctoDevelopment** [GoranM/bdx#607]
Hi! I'm creating a game in Blender using BDX. When I add an additional scene, the game closes immediately and I get this output in the console:
```
------------ BDX START --------------------------------------------------

Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
Controllers: added manager for application, 1 managers active
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at de.krgames.testgame.Sacky.main(Sacky.java:76)
        at com.nilunder.bdx.Scene.runObjectLogic(Scene.java:804)
        at com.nilunder.bdx.Scene.update(Scene.java:847)
        at com.nilunder.bdx.Bdx.main(Bdx.java:249)
        at de.krgames.testgame.BdxApp.render(BdxApp.java:29)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:218)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)

BUILD SUCCESSFUL

Total time: 1.749 secs

------------ BDX END ----------------------------------------------------
```

What am I doing wrong?

**Comment by rafcolson** [comment]
Hi,

It means that line 76 of your ```Sacky.java``` contains a call to a method or field of an object that is ```null```. That's all I could say about it because you I don't know what you're doing exactly.

If you're not sure that the issue you're having is a development issue (bug or design), it's probably better to [Community/Support](http://www.reddit.com/r/bdx).

**Comment by OctoDevelopment** [comment]
Btw this happens almost evertime I add something eg. a lamp or a cube. It says there is a NullPointerException in Scene.java, but this file doesn't exist, even though I made internal Java files external.

**Comment by rafcolson** [comment]
It would help if you would copy/paste your Sacky.java between code tags. For example:
```java
// paste your code here
```

**Comment by OctoDevelopment** [comment]
This is my Sacky.java:
```java
package de.krgames.testgame;

import com.nilunder.bdx.*;
import com.nilunder.bdx.Scene.*;
import com.nilunder.bdx.utils.*;
import javax.vecmath.Vector3f;

public class Sacky extends GameObject {
    
    private float MovementSpeed = 15.0f;
    
    private boolean IsGrounded = true;

    private float MaxSpeed = 6.052631578947368f;
    private boolean IsBelowNegativeFive = false;
    
    public void main() {

        Bdx.imaps.put("left", "k:left", "g:left");
        Bdx.imaps.put("right", "k:right", "g:right");

        if (Bdx.keyboard.keyHit("space")) {
            if (IsGrounded == true) {
                Bdx.sounds.get("Jump").play();
                applyForce(0, 0, 350);
            }
        }
        if (Bdx.keyboard.keyDown("left")){
            applyForce(-1 * MovementSpeed, 0, 0);
        } else if (Bdx.keyboard.keyDown("right")){
            applyForce(1 * MovementSpeed, 0, 0);
        }
        
        if (touchingProperty("canWalk")){
            IsGrounded = true;
        } else {
            IsGrounded = false;
        }

        Vector3f vel = velocity();

        vel.x = vel.x * 0.95f;

        if (vel.x > MaxSpeed) {
            vel.x = MaxSpeed;
        } else if (vel.x < -MaxSpeed) {
            vel.x = -MaxSpeed;
        }
        if (position().y != 0) {
            position(position().x, 0, position().z);
        }

        if (position().z < -5) {
            if (IsBelowNegativeFive == false)
                Bdx.sounds.get("Death").play();
            IsBelowNegativeFive = true;

            int shadefac = 0;
            if (Math.round((15 + position().z) * 10) > 0) {
                shadefac = Math.round((15 + position().z) * 10);
            }
            Bdx.display.clearColor(darkenHexColor("C7C7FF", shadefac)); //5FAFFF
            float x =  Math.round((15 + position().z) * 10) / 100f;
            Bdx.scenes.get("Scene").ambientLight(new Color(x,x,x,1));
        } else {
            IsBelowNegativeFive = false;
            Bdx.display.clearColor(darkenHexColor("C7C7FF", 100));
            Bdx.scenes.get("Scene").ambientLight(new Color(1,1,1,1));
        }

        if (hit("KillPlane")) {
            velocity(0, 0, 0);
            rotate(0, 0, 0);
            position(0, 0, 4);
        }
        
        velocity(vel);
    }

    public static Color parseColor(String hex) {  
        String s1 = hex.substring(0, 2);  
        int v1 = Integer.parseInt(s1, 16);  
        float f1 = (float) v1 / 255f;  
        String s2 = hex.substring(2, 4);  
        int v2 = Integer.parseInt(s2, 16);  
        float f2 = (float) v2 / 255f;  
        String s3 = hex.substring(4, 6);  
        int v3 = Integer.parseInt(s3, 16);  
        float f3 = (float) v3 / 255f;  
        return new Color(f1, f2, f3, 1);  
    } 

    public static Color darkenHexColor(String hex, int shadeFactor) {  
        String s1 = hex.substring(0, 2);  
        int v1 = Math.round((Integer.parseInt(s1, 16) / 100) * shadeFactor);  
        float f1 = (float) v1 / 255f;  
        String s2 = hex.substring(2, 4);  
        int v2 = Math.round((Integer.parseInt(s2, 16) / 100) * shadeFactor);  
        float f2 = (float) v2 / 255f;  
        String s3 = hex.substring(4, 6);  
        int v3 = Math.round((Integer.parseInt(s3, 16) / 100) * shadeFactor);  
        float f3 = (float) v3 / 255f;

        return new Color(f1, f2, f3, 1); 
    }  
    
}
```

**Comment by rafcolson** [comment]
Which is line 76? (your code has an empty line on 76)

**Comment by OctoDevelopment** [comment]
Line 76 is now line 74 because I removed a comment at the beginning that I didn't need anymore.

**Comment by rafcolson** [comment]
Where is the code to add the scene?

**Comment by OctoDevelopment** [comment]
I added the scene directly in Blender.

**Comment by rafcolson** [comment]
There's the problem. Adding a scene in Blender won't add the scene to the list of "active" scenes in BDX.

You should probably add this to the top of your code:

```java
	public void init(){
		Bdx.scenes.add("Scene");
	}
```

**Comment by OctoDevelopment** [comment]
Thanks! Problem solved!

**Comment by rafcolson** [comment]
You're welcome. Feel free to ask for support at https://www.reddit.com/r/bdx/ anytime.
