### ISSUE TITLE
Suggestion: Option for higher res text

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#693]
Hey!

I know that there has been a thread for this before, but this is going at the problem with a different approach.

Right now we're using Hiero to generate BitMapType fonts. This becomes a little bit of a hassle when we are not using blocky fonts or want big text. Either we make the text small enough so the pixelation is hidden or we play around with Hiero to get a higher resolution text. I don't think any of these solutions are very good.

My suggestion is my not have the option to use to use the FreeTypeFontGenerator?
https://github.com/libgdx/libgdx/wiki/Gdx-freetype

I understand that we might have to give up a little bit of speed, but if text is used sparingly, this shouldn't be much of a problem. I'm not suggesting to remove the already implemented text handling, just have another for anyone who wants to give up a little bit of frames for nicer text.

Anyways, here is a rough result with FreeType I did with BDX (very hacky solution right now):
![image](https://cloud.githubusercontent.com/assets/4584511/16179119/bc11df28-362a-11e6-8d57-146c30dd45c0.png)
This is 72 font size on a 1080x720 display. Looks pretty nice if you ask me.

Sadly, it seems that my hacky solution killed the profiler, so I wasn't able to check the ongoing frame rate.

I'd be happy to implement this feature, just wondering if anyone else is interested?

**Comment by rafcolson** [comment]
This would be very cool, but why not replace Hiero altogether? It would be great if Text objects in BDX wouldn't have such a low resolution and wouldn't have incorrect sizes and spacings. If this can be fixed with FreeTypeFontGenerator along with getting these extra features for text, then wouldn't that be worth the change?

You can get the tickRate like this:
```java
float f = Bdx.profiler.avgTickRate;
```

**Comment by Lucrecious** [comment]
Like I said on the post, I think the way Goran has implemented the Text in BDX allows for text in 3D space. This would be an overlay over everything (I'm not quite sure how to do this in 3D space, I think it'd be hacky at best).

**Comment by rafcolson** [comment]
Ah, okay. Thanks for reminding me.

**Comment by SolarLune** [comment]
Hmm, well, we could add something that would render objects on top of the scene, like the BGE's `postDraw` callback.

Maybe the better solution would be to just see about improving text, all around. If it's possible to render text onscreen using Gdx-freetype, then maybe it's possible to render the text to a texture that is displayed on a plane in 3D space? We'd still have 3D text, but we'd be able to take advantage gdx-freetype, like being able to control how large the text point size is, or if there's shadows or outlines.

I'm sure @GoranM has some ideas on ways we could improve text (if it's possible to improve at all) / alternative methods of getting text into BDX.

**Comment by Lucrecious** [comment]
I agree, I'll probably sit on it for a little. Both to see what Goran says about it and also because I'm busy for the next week.

On another note, I can't think of any situation where I'd want dynamic text in 3D space anyways.  If I really wanted some sort of text in the background, I'd probably just make a texture with the text on it and UV map it on an object..

**Comment by GoranM** [comment]
I think gdx-freetype is a wrapper around the native freetype library. If that's true, I don't think it's compatible with the GWT compiler.

That's basically the core reason for why we use pre-rendered bitmap fonts (created at build-time), instead of generating them dynamically (at runtime). It's not really a limitation of the Hiero library, because if you look at Hiero dependencies, you can see that it's actually using gdx-freetype, so it can do the same thing; The core problem is that it's not supported by the HTML5 backend, so we can't use it to render fonts at runtime.

Regarding screen-space vs world-space text: It may not look "pixel perfect", but the latter provides more leverage, because you can treat text just as another GameObject, which can be positioned and oriented like any other element in the editor. That's quite convenient, even when you're just setting up a purely 2D UI (especially when you have other elements in the ui that need to align precisely with the text).

The whole "blocky" look is largely an issue with the resolution at which the bitmap font was rendered - Everything else can be adjusted to make things look proper (more or less).

**Comment by SolarLune** [comment]
> On another note, I can't think of any situation where I'd want dynamic text in 3D space anyways. If I really wanted some sort of text in the background, I'd probably just make a texture with the text on it and UV map it on an object..

Well, 3D UIs have gotten popular (i.e. Split/Second comes to mind). BDX isn't at the graphical capability to support those types of games, but it's still nice to be able to use 3D text.

> The whole "blocky" look is largely an issue with the resolution at which the bitmap font was rendered - Everything else can be adjusted to make things look proper (more or less).

Well, given that we don't really have access to the Hiero modified source, would it be possible to use one of the [alternatives available](https://github.com/libgdx/libgdx/wiki/Hiero#bitmapfontwriter) that provide command-line options?

**Comment by Lucrecious** [comment]
> Well, 3D UIs have gotten popular (i.e. Split/Second comes to mind). BDX isn't at the graphical capability to support those types of games, but it's still nice to be able to use 3D text.

That's fair. 

> It may not look "pixel perfect", but the latter provides more leverage, because you can treat text just as another GameObject, which can be positioned and oriented like any other element in the editor. That's quite convenient, even when you're just setting up a purely 2D UI (especially when you have other elements in the ui that need to align precisely with the text).

Text not looking "pixel perfect" is kind of a big deal for me. Also, with a little bit of math, I'm sure we can still use text objects to position text on 2D space (more or less). And, to be fair, it's not that easy to position things with the already implemented Text object because of the discrepancy in Blender text and Hiero generated text. 

>The whole "blocky" look is largely an issue with the resolution at which the bitmap font was rendered - Everything else can be adjusted to make things look proper (more or less).

The "convenience" of being able to line up my UI in Blender is killed if I mess with the text resolution on Hiero (again because of size discrepancies).

>The core problem is that it's not supported by the HTML5 backend, so we can't use it to render fonts at runtime.

I don't really mind losing HTML 5 support (for an optional Text dependancy I mean). It's another reason why I suggested another option and not to delete the one that's already there.

**Comment by rafcolson** [comment]
>it's not that easy to position things with the already implemented Text object because of the discrepancy in Blender text and Hiero generated text.

I agree. It looks like `BitmapFontWriter` might be a good alternative, @SolarLune @GoranM ?

**Comment by GoranM** [comment]
> Well, given that we don't really have access to the Hiero modified source, would it be possible to use one of the alternatives available that provide command-line options?

It's software, so virtually anything is possible, but you would need something that can generate not only the font texture, but also the angel code that is used to map each glyph to where it's actually located on that texture.

As raf mentioned, BitmapFontWriter looks like it could work.

> with a little bit of math, I'm sure we can still use text objects to position text on 2D space (more or less). And, to be fair, it's not that easy to position things with the already implemented Text object because of the discrepancy in Blender text and Hiero generated text.

I think it's somewhat more involved than just "a little bit of math".

Unlike geometry, which remains at a consistent size relative to accompanying geometry (even when the projection matrix changes), the size of a string rendered directly into the visible framebuffer will vary based on the resolution.

So, not only would you have to compensate for the existing discrepancy leading out from blender at build time, but also the unpredictable, resolution-driven discrepancy that would become visible at runtime.

> I don't really mind losing HTML 5 support (for an optional Text dependancy I mean).

I'm not sure if we can actually build the HTML5 project if there's engine code that references an unwrapped native library. I don't think GWT would be able to resolve that.

**Comment by SolarLune** [comment]
> Edit: Ideally the alternative would enable us to generate text blocks instead of one line of text too.

Cool, that's another thing we're missing.

So [looking at the example](https://github.com/libgdx/libgdx/wiki/Hiero#bitmapfontwriter), we'd create a Java program that uses `gdx-tools.jar` and BitmapFontWriter to generate the necessary font files? But we can't actually include that in BDX as part of the engine, as it's not GWT-compatible?

**Comment by Lucrecious** [comment]
>Unlike geometry, which remains at a consistent size relative to accompanying geometry (even when the projection matrix changes), the size of a string rendered directly into the visible framebuffer will vary based on the resolution.

I see. I thought the process would be different since we're dealing with pixels. If we had an object like a plane in Blender, is has a size in pixels on the screen and we could choose a font size to represent the pixel length of the plane. As you noted, the size is affected by resolution which is apparently unpredictable.

**Comment by GoranM** [comment]
> So looking at the example, we'd create a Java program that uses gdx-tools.jar and BitmapFontWriter to generate the necessary font files?

Yes. It would be a replacement for the custom version of Hiero that currently ships with BDX, and it would serve the same purpose (to generate the necessary font textures and data at build time), while offering additional benefits (ability to set resolution, and whatever else we need).

> But we can't actually include that in BDX's source as part of the engine, as it's not GWT-compatible?

Yes, because the gdx-freetype library, on which Hiero and BitmapFontWriter both depend, is simply a wrapper around the native freetype lib, instead of being a pure Java implementation.

GWT can only compile Java (as far as I know).

**Comment by Lucrecious** [comment]
Hey!
Here's a small demo on high resolution text in BDX and how it looks like so far:
https://youtu.be/gWIsFzP4cow

Setup:
1. Make a text object
2. Give the text object a property called "truefont"
3. Give the text a font that is in "assets/bdx/fonts/" in .ttf format (other formats could later be supported, I just decided to hardcode the .ttf extension for some reason)
4. Add two empties to define the size of the text on the y-axis for the camera

Limitations:
- No 3D movement or rotation (don't know how easy this is to implement)
- No 2D rotation (doesn't seem that hard to implement, but I don't need it, so not implemented as of now)
- Can't deploy to HTML (there doesn't seem to be a solution to this problem with the current library)
- The size of the text is determined by two empties, not automatically. As far as I know, because of font size ambiguity, it's not possible to know how big text should be otherwise.

You give up a little bit of convenience upon setup, some functionality upon usage and you give up web development.

On the other hand, you gain perfect fidelity between what you see in Blender and what you see in BDX with whatever font you like (for location and size at least), you can change the size of the text on the fly without having to worry about resolution and you get nicer looking text.

Again, there's still full access to BDX's original text setup, but now there's an extra option with this "add-on".

**Comment by SolarLune** [comment]
Yo! 

This looks cool, but I still think it might be best to solve the core problems with text, rather than introduce an alternative that solves those problems, but brings up others.

The core problems with text in BDX currently seem to be:

- Text is somewhat low resolution by default, basically. This should be easy to solve by simply outputting higher resolution textures from the BitmapFontWriter class.

- Text is of an indeterminate size in relation to Blender. What was the problem that made this not possible to resolve, @GoranM?

- Newline characters aren't supported. We should be able to just support newlines ourselves by scanning text to determine if there are any newline characters, and properly splitting and rendering the text on the next "line" down, on the object's local Z axis.

**Comment by Lucrecious** [comment]
Fully agree, again, this was just kind of like a window on what we _could_ have. I would much rather "fix" the text we already have. However, I found it difficult because of the Hiero dependancy - I don't really have access to it's modified source.

I still think we should use some sort of library that auto-generates the BitmapFont, mostly because it gives us a lot more information and functionality pertaining to text - height of capitals in pixels, width of letters in pixels, alignment, scale, etc.

**Comment by GoranM** [comment]
Nice demo.

Like SolarLune, I think it would be best to solve this at the root, and you seem to agree with that, so:

> I found it difficult because of the Hiero dependancy - I don't really have access to it's modified source.

The sources to the modified Hiero program were lost, so we would basically need to recreate that program as a first step to improving things in this context.

As discussed before, it should be possible to create an alternative with BitmapFontWriter.

-

> Text is of an indeterminate size in relation to Blender. What was the problem that made this not easy to resolve, GoranM?

Blender seems to interpret font metrics in a way that Hiero doesn't.

**Comment by Lucrecious** [comment]
Just wanted to point out that with BitmapFonts, since we have access to individual character widths in pixels (among other things), we can translate those into 3D coordinates to get some pretty precise text manipulation:
https://gyazo.com/a7ef394c268dd02cfe47eab1b55f2880

**Comment by SolarLune** [comment]
Yo, I took a crack at this, and I've got the app up and running. Also got a repo for it here on GitHub here: https://github.com/SolarLune/BDXFontWriter

Here's a test output.

![allerdisplay](https://cloud.githubusercontent.com/assets/4733521/17320982/178c3afa-584b-11e6-956e-c7164301ec2b.png)

I'm guessing the idea is that @Goran can make a fork of the repo and that can be the new master for everybody?

As for actual usage, I'm guessing that we could just compile the app down to a .JAR and then pass it a JSON string for the settings for each font resource from Blender (like we're doing for everything else). That way we could tell the app the settings for each font (what it's called, what resolution to render the text at, etc), and make coordinated buttons and sliders and stuff in the font panel for BDX (so you can change if it has a shadow, what color it is, etc).

After running the program, given a font file named `AllerDisplay.ttf`, I'm left with two files in an output folder - `AllerDisplay.fnt` and `AllerDisplay.png`. Goran told me some time ago that we need to convert `.fnt` files to `.fntx`, which we should be able to do by copying the [exporter's method](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L750), though I guess we could also just have the exporter convert the font files after it's finished running the Writer JAR on each font resource in the blend file?

**Comment by GoranM** [comment]
> I'm guessing the idea is that @Goran can make a fork of the repo and that can be the new master for everybody?

The BDXFontWriter repo is not a BDX fork, so I'm not sure how it could be made into a "new master for everybody".

You need to make a PR that adds the source code to the extern directory, along with a build.xml that will generate the jar to replace blender/bdx/gen/hiero/gdx-tools.jar.

Then you need to modify the exporter to use your jar.

> I guess we could also just have the exporter convert the font files after it's finished running the Writer JAR on each font resource in the blend file?

It's already doing that, so it's probably best to just use the existing system (at least for now).

**Comment by SolarLune** [comment]
OK, so I'm looking into this again now. 

I'm getting there, but right now I'm stuck on the building process. The FontWriter class can't find LibGDX's FreeTypeFontGenerator, despite the new `FontWriter/build.xml` file pointing to the `gdx-tools` directory in its `master-classpath` node. 

Here's the branch as it stands:

https://github.com/SolarLune/bdx/tree/fontwriter

Any ideas?

**Comment by GoranM** [comment]
You mean the build process for extern/fontwriter can't find LibGDX's FreeTypeFontGenerator? I don't think the BDXFontWriter class is actually doing anything at build-time.

Are you sure that it's ok to use all lowercase property names (ie: your use of usenativebasedir vs my use of useNativeBasedir)? The documentation examples all use camel-case, so maybe that has something to do with it. Whatever the case may be, I think we should keep that consistent with how it's outlined in the docs (camel-case).

Are you sure that FreeTypeFontGenerator resides in the one of the jars that you included in your classpath? Did you confirm that this jar actually exists on your system, and that it's in the right place?

What is the actual error that you're getting?

**Comment by SolarLune** [comment]
> You mean the build process for extern/fontwriter can't find LibGDX's FreeTypeFontGenerator? I don't think the BDXFontWriter class is actually doing anything at build-time.

Yeah, BDX as a whole refuses to build because it's failing on BDXFontWriter, which requires FreeTypeFontGenerator.

> Are you sure that FreeTypeFontGenerator resides in the one of the jars that you included in your classpath? Did you confirm that this jar actually exists on your system, and that it's in the right place?

Yeah, the Generator is in `gdx-tools.jar`, and it definitely exists on my system; I modified the project gradle files, and it did download the necessary dependencies.

> Are you sure that it's ok to use all lowercase property names (ie: your use of usenativebasedir vs my use of useNativeBasedir)? The documentation examples all use camel-case, so maybe that has something to do with it. Whatever the case may be, I think we should keep that consistent with how it's outlined in the docs (camel-case).

Hmm, changing it didn't seem to do anything, and there are other non-camelCase property names in there.

> What is the actual error that you're getting?

Here are the errors:

```
build-fontwriter:
    [javac] Compiling 1 source file to /home/solarlune/Tools/bdx/extern/fontwriter/build
    [javac] /home/solarlune/Tools/bdx/extern/fontwriter/src/com/solarlune/BDXFontWriter.java:6: error: package com.badlogic.gdx.graphics.g2d.freetype does not exist
    [javac] import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
    [javac]                                              ^
    [javac] /home/solarlune/Tools/bdx/extern/fontwriter/src/com/solarlune/BDXFontWriter.java:22: error: cannot find symbol
    [javac]         FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.absolute(inputFontPath));
    [javac]         ^
    [javac]   symbol:   class FreeTypeFontGenerator
    [javac]   location: class BDXFontWriter
    [javac] /home/solarlune/Tools/bdx/extern/fontwriter/src/com/solarlune/BDXFontWriter.java:22: error: cannot find symbol
    [javac]         FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.absolute(inputFontPath));
    [javac]                                               ^
    [javac]   symbol:   class FreeTypeFontGenerator
    [javac]   location: class BDXFontWriter
    [javac] /home/solarlune/Tools/bdx/extern/fontwriter/src/com/solarlune/BDXFontWriter.java:23: error: package FreeTypeFontGenerator does not exist
    [javac]         FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
    [javac]                              ^
    [javac] /home/solarlune/Tools/bdx/extern/fontwriter/src/com/solarlune/BDXFontWriter.java:23: error: package FreeTypeFontGenerator does not exist
    [javac]         FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
    [javac]                                                                                          ^
    [javac] /home/solarlune/Tools/bdx/extern/fontwriter/src/com/solarlune/BDXFontWriter.java:33: error: package FreeTypeFontGenerator does not exist
    [javac]         FreeTypeFontGenerator.FreeTypeBitmapFontData data = generator.generateData(parameter);
    [javac]                              ^
    [javac] 6 errors
```

**Comment by GoranM** [comment]
> the Generator is in gdx-tools.jar

How did you confirm that?

Looking at the error messages, it seems that the class in question is in the freetype package, which would suggest that it resides in the gdx-freetype jar.

**Comment by SolarLune** [comment]
Whoops!

My mistake on that - I thought it was in `gdx-tools.jar`. Adding `gdx-freetype.jar` to the dependencies list helped. 

So the problem I'm running into now is that I can't simply have the BDXFontWriter class extend ApplicationAdapter like a normal LibGDX project, because it's just a single class file; I think I need to set up an entire LibGDX project, right? Should I put it in the `extern` directory?

**Comment by SolarLune** [comment]
No, wait, BDX as a whole uses LibGDX packages without being a gradle project and packages it all up into `bdx.jar` successfully. But then again, it's not being directly run like I'm trying to do with the FontWriter class - we have `DesktopLauncher` (and other Launchers) for actually running the projects; maybe that's what's missing? 

Anyway, any ideas of how to proceed? The problem I've been looking at currently is that I have to add a `main()` function to my class to have the `.jar` be executable. So, I made the FontWriter class not extend `ApplicationAdapter` anymore and added a `main()` function, but when I run the `.jar`, I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/tools/bmfont/BitmapFontWriter$FontInfo
	at com.solarlune.fontwriter.FontWriter.main(FontWriter.java:13)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.tools.bmfont.BitmapFontWriter$FontInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

I've updated the branch with my current code.

**Comment by GoranM** [comment]
How are you actually running the program?

Note [the way in which we run Hiero](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L730-L740), where the classpath is provided via the `-cp` switch. Looking at the error, I would assume that you either forgot to provide the classpath, or the provided classpath is incorrect in some way.

Also, you may find this [BitmapFontWriter example](https://github.com/libgdx/libgdx/wiki/Hiero#bitmapfontwriter) to be helpful.

**Comment by SolarLune** [comment]
Hmm, OK, thanks.

The current approach I'm trying is to just have the .jar be runnable as a base, like so:

```
java -jar ./fontwriter.jar 
```

So I guess the problem I'm running into is that the .jar file can't find the classes without adding them to Java's class path.

I notice the paths in the master-classpath attribute in build.xml; is it not possible to add that same info to a "Class-Path" attribute in the build-fontwriter-jar target? I think I'd rather not hard-code the paths to run using the -cp flag, if possible  - it seems like it'd be easier in the long-term to have Java point to the classes in the .jar's manifest, rather than doing it ourselves in Python when invoking Java.

**Comment by SolarLune** [comment]
Never mind for what I was saying, because specifying the class-path doesn't work (so doing it in the build.xml file might also not work). Let's just try getting it to work first, then we can try to improve things.

_____

So the way I'm executing the jar file is thusly: I run `java -cp "/home/solarlune/Tools/bdx/blender/bdx/libs/fontwriter.jar:" com.solarlune.fontwriter.FontWriter`. After that ":" after the fontwriter.jar file, I put the other LibGDX tool / FreeType .jar files.

When I do things this way, I get a JNI error, but seemingly only if the source file actually contains Font-related classes and methods (i.e. if it's just a print statement, the .jar runs fine):

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator$FreeTypeBitmapFontData
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator$FreeTypeBitmapFontData
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

**Comment by GoranM** [comment]
Please post the complete command, exactly as you ran it.

**Comment by SolarLune** [comment]
OK, I've found an issue that I forgot about that I fixed (I forgot that I implemented your suggestion of how to use Hiero). Now I'm in the process of stitching each .jar path into the java command; am I right in the way I'm going about this? Because it's slow-going - this is what I've got so far:

```
java -cp "/home/solarlune/Tools/bdx/blender/bdx/libs/fontwriter.jar:/home/solarlune/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.9.2/d710a8704ed584ec2ba9ca52e3a6a5885dd759cc/gdx-backend-lwjgl-1.9.2.jar:/home/solarlune/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.9.2/e641cb91bec06bc64d9ddf7a7d7062caceec73cd/gdx-1.9.2.jar:/home/solarlune/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.2/a9d80fe5935c7a9149f6584d9777cfd471f65489/lwjgl-2.9.2.jar:/home/solarlune/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-tools/1.9.2/37d8e3009ae0febdf93717b21980c67c8cadac07/gdx-tools-1.9.2:/home/solarlune/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/dde4cf7e9ce61c24042f512203aed87657496639/gdx-platform-1.9.2-natives-desktop" com.solarlune.fontwriter.DesktopLauncher

```

**Comment by GoranM** [comment]
You didn't include the freetype jars, which would explain the freetype related errors.

It also seems like you have entries that are not jars ... Did you just forget to append the ".jar", or is there some other reason?

In general, to solve these "class definition not found" issues, you need to figure out the jar in which that class resides, and then make sure that a path to that jar is included in the classpath.

**Comment by SolarLune** [comment]
OK, I finally got it all working (mostly). Thanks for the tips - I was missing those ".jar" endings. I think I'm almost there - I got the font exported from Blender and the texture is exported with the modifications (outline, shadows, etc.), but the texture appears garbled when displayed in BDX. Any thoughts? Maybe Hiero's code generation is different from BitmapFontWriter's?

Here's a shot - the text is supposed to display "ABC."

![screenshot from 2016-09-13 00-33-01](https://cloud.githubusercontent.com/assets/4733521/18465084/a8a22972-7949-11e6-8310-e1a45356fb68.png)

The current settings can be seen in the DesktopLauncher.java class - notice that I'm using a size of 512x512 for the font texture. I tried 256x256 as well, but the text was invisible (probably just misaligned UVs (?), like the current problem).

I've updated my branch, as usual.

**Comment by GoranM** [comment]
> Maybe Hiero's code generation is different from BitmapFontWriter's?

You can test that by rendering the same font with both Hiero and BitmapFontWriter (at the same resolution), and then comparing the generated files (png and fnt/x) to see if there are any discrepancies.

-

You're instancing PixmapPacker with a 1024 by 1024 resolution, but calling writeFont with 512 by 512. In the example program I referenced before, the resolution values passed to PixmapPacker are the same as those passed to writeFont, so maybe that's a requirement that you need to follow as well.

**Comment by SolarLune** [comment]
> I agree. It looks like BitmapFontWriter might be a good alternative, @SolarLune @GoranM ?
Edit: Ideally the alternative would enable us to generate text blocks instead of one line of text too.

OK, the first time I read this, I thought you were saying that alternatives would enable us to generate text blocks - I must've misread it initially. You were just saying that it would be a nice feature to add?

> You're instancing PixmapPacker with a 1024 by 1024 resolution, 

Ah, that was the issue! Thanks a lot, that fixed it. Now it seems to be working nice and smoothly.

OK, so we'll need some way of tweaking how the font objects are configured - doing so through the Blender GUI would probably be a good idea, but there's not really any customize-able zone dedicated to font data.

**Comment by rafcolson** [comment]
>OK, the first time I read this, I thought you were saying that alternatives would enable us to generate text blocks

That's what I meant. When the spacing between and the size of every character is known, it shouldn't be hard to calculate when a new line should start. A text "block" then should have a width and probably a margin too.

>You were just saying that it would be a nice feature to add?

No. I meant that it would be ideal if BitmapFontWriter or some other package would already have this feature. But if not, I don't think it would be so hard to add it ourselves, if we can attain information about character dimension and spacing easily and with precision of course. This isn't the case with how Hiero was integrated, that's for sure.

**Comment by Lucrecious** [comment]
> When the spacing between and the size of every character is known, it shouldn't be hard to calculate when a new line should start. A text "block" then should have a width (and a height) and probably a margin too.

I agree. It's very useful to know the dimension of individual characters. Although, a text block might have width/height in pixels and not the 3D units LibGDX uses. If @SolarLune finds a solid relationship between the pixels and the 3D units this would work (not too difficult). Also, I can't see how this might solve the Blender to LibGDX (BitmapFontGen) discrepancy. I solved this issue pretty hastily with two empties (for size). You guys are probably looking for a cleaner solution though.

So far, this is looking cool. I might switch over to it if it turns out okay :) Right now I'm using an upgraded version of the text I showed off on the OP.

**Comment by SolarLune** [comment]
> But if not, I don't think it would be so hard to add it ourselves, if we can attain information about character dimension and spacing easily and with precision of course. This isn't the case with how Hiero was integrated, that's for sure.

Hmm, yeah, I don't _think_ any other package has that feature, though I haven't really checked too hard. 

> I still think we should use some sort of library that auto-generates the BitmapFont, mostly because it gives us a lot more information and functionality pertaining to text - height of capitals in pixels, width of letters in pixels, alignment, scale, etc.

> If @SolarLune finds a solid relationship between the pixels and the 3D units this would work (not too difficult). Also, I can't see how this might solve the Blender to LibGDX (BitmapFontGen) discrepancy. 

We might still be able to get that information by generating the BitmapFont, I think, and then passing it on to a file or something for BDX to use on runtime? We wouldn't use the BitmapFonts themselves, but we might be able to get data from them, even if they're incomplete. I'll have to take a look to see if I can figure something out, I guess.

________

So the current to-do list is something like:

- ~~Support the Freetype options (Shadow, outline, color, etc)~~
- Add ability to set these options somehow per-font
- Add function to get the size of each character in the string (?)
- Add newline character support
- Support different alignments (left, right, center)?
- Add textbox support? (Which already has an option in Blender, which is cool)

________

So to set the options, we could do so through Blender's GUI, or through a separate interface, like a text file. The text file approach is simpler, but the GUI is obviously more coherent. Then again, you won't see the changes live in Blender, so it really doesn't have to be there, and there's no existing location for font options (text objects have their own, individual settings). We could add to a panel somewhere if necessarily, I suppose, though we'd have to find and share settings between font types.

The file approach is simpler -  I think we'd just create a settings file (probably simple JSON) that indicates how the font should be displayed (outline, color, shadow, etc). When the user boots their project up, BDX will create the settings file if it doesn't exist, and load it to generate the fonts if it does.

Note that we'd have to re-run the font generation process for each font if its settings file gets modified.

**Comment by GoranM** [comment]
> I don't think it would be so hard to add it ourselves, if we can attain information about character dimension and spacing easily and with precision of course. This isn't the case with how Hiero was integrated, that's for sure.

As far as I know, BitmapFontGenerator doesn't produce additional font data; It's the same angel-code output we got with Hiero, so the range of possibilities is largely unchanged.

@SolarLune 

Couldn't we simply add a custom property in the existing font properties panel for things like resolution?

Also, I would suggest keeping the first PR simple. Just replacing the existing Hiero setup, with the ability to change resolution, and set outline/shadow should be enough for now.

**Comment by rafcolson** [comment]
>As far as I know, BitmapFontGenerator doesn't produce additional font data; It's the same angel-code output we got with Hiero, so the range of possibilities is largely unchanged.

I've done tests before. There's no problem with getting all necessary font data with Hiero. I had to rewrite `Text.text()` in order to get accurate results. I think I saved it somewhere.. have to look.

The only problem with Hiero I can think of is that we can't change resolution.

**Comment by SolarLune** [comment]
> Couldn't we simply add a custom property in the existing font properties panel for things like resolution?

Well, the font properties panel is still per-object, right? I guess we could tie in our additions to make the properties work across font objects?

> Also, I would suggest keeping the first PR simple. Just replacing the existing Hiero setup, with the ability to change resolution, and set outline/shadow should be enough for now.

OK, that sounds fine.

**Comment by Lucrecious** [comment]
> Well, the font properties panel is still per-object, right? I guess we could tie in our additions to make the properties work across font objects?

Wouldn't we want to change the resolution per-object? (Higher res resolution for larger text, lower res for smaller text).

**Comment by GoranM** [comment]
> Well, the font properties panel is still per-object, right?

The properties correspond to the blender Font object. Multiple Text objects can reference the same Font object, just like multiple objects can reference the same mesh.

-

> Wouldn't we want to change the resolution per-object? (Higher res resolution for larger text, lower res for smaller text).

Each new resolution would essentially define a new font, because it would require generating a unique texture, with corresponding font data, at build time.

So, per-font seems like the more sensible approach in this context.

**Comment by SolarLune** [comment]
OK, so I think I got it. 

The only real problem I have currently is that LibGDX'll split the exported text images up into multiple images if it so feels the need. That can cause a crash as well, because it'll name the images "blah_0.png", "blah_1.png", rather than "blah.png", which is what BDX will try to load.

The profiler will need to be updated for whatever game projects are currently under way, or you'll need to delete the profiler scene currently in the project's scenes folder if there's on already.

Anyway, PR submitted.

**Comment by rafcolson** [comment]
Maybe I could prepare a fix for the profiler so this could be evaluated immediately after this is merged. I think I'll be needing a week or so.

**Comment by Lucrecious** [comment]
Looks cool! @SolarLune - I left a comment asking a couple of questions.

**Comment by SolarLune** [comment]
"If it so feels the need" - that's if the font size makes the font too large to fit on the source texture. I considered automatically setting the resolution based on the font size, but that might not be a good idea if it doesn't scale linearly, or if there are more characters in the font than usual.

> Maybe I could prepare a fix for the profiler so this could be evaluated immediately after this is merged. I think I'll be needing a week or so.

I'm not quite sure what you're referring to, but this does require that you re-export the profiler scene (so, delete the existing one in the scenes folder of your project) because the font in the profiler blend file no longer points to the `hiero` directory (because it was renamed to `fontgen`).

**Comment by SolarLune** [comment]
PR updated to add font color and alpha (so you don't have to have white text / modify the "main" part of text. Now you can, say, make the shadows or the outline white, and modify that color as you wish).

**Comment by rafcolson** [comment]
>I'm not quite sure what you're referring to

Okay, sorry. I think I just misunderstood. Thought that you meant that the profiler was broken. Great work!

**Comment by SolarLune** [comment]
> Okay, sorry. I think I just misunderstood. Thought that you meant that the profiler was broken. Great work!

Yeah, sorry, there's nothing wrong with the profiler. It's just that the font was pointing to the old folder. Thanks!
