### ISSUE TITLE
Can't build desktop demo El Capitan

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#749]
Having same issue as https://github.com/GoranM/bdx/issues/11

I don't want to uninstall my system Java. How can I update the CLASSPATH to avoid this crash?

------------ BDX START --------------------------------------------------
 
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
2016-08-11 14:11:48.122 java[11621:315363] 14:11:48.122 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Controllers: added manager for application, 1 managers active
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.NoSuchMethodError: javax.vecmath.Vector3f.div(Ljavax/vecmath/Vector3f;)Ljavax/vecmath/Vector3f;
	at com.nilunder.bdx.GameObject.updateLocalScale(GameObject.java:679)
	at com.nilunder.bdx.GameObject.parent(GameObject.java:198)
	at com.nilunder.bdx.GameObject.parent(GameObject.java:169)
	at com.nilunder.bdx.Scene.hookParentChild(Scene.java:430)
	at com.nilunder.bdx.Scene.init(Scene.java:377)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:108)
	at com.leo.test5.BdxApp.create(BdxApp.java:18)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

BUILD SUCCESSFUL

Total time: 2.977 secs
 
------------ BDX END ----------------------------------------------------

**Comment by songproducer** [comment]
Fix:

Restart while holding cmd + r
Utilities > Terminal
csrutil disable
reboot 

sudo rm /System/Library/Java/Extensions/vecmath.jar 

Restart while holding cmd + r
Utilities > Terminal
csrutil enable
reboot

**Comment by SolarLune** [comment]
Hey, thanks for this - this is very useful information for fixing this particular bug!
