### ISSUE TITLE
All text doesn't render correctly

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#751]
Trying to render text in the Sacky demo but it comes out as a small, black square.

![](http://i.imgur.com/oe3uKmp.png)

Following fixes regarding missing fonts and textures from here: https://github.com/GoranM/bdx/issues/571#issuecomment-192567769

I get this:
`Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Unable to extract LWJGL natives.
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:67)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:79)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:67)
	at com.badlogic.gdx.tools.hiero.Hiero.main(Hiero.java:1544)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: liblwjgl.dylib
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:126)
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:148)
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:59)
	... 3 more
 
------------ BDX START --------------------------------------------------
 
Configuration on demand is an incubating feature.
:core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: /Users/leotreasure/bdx/test5/core/src/com/leo/test5/Sacky.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:core:processResources UP-TO-DATE
:core:classes
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
2016-08-14 12:05:32.562 java[16870:661846] 12:05:32.562 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Controllers: added manager for application, 1 managers active
warning CollisionDispatcher.needsCollision: static-static collision!
Controllers: removed manager for application, 0 managers active

BUILD SUCCESSFUL

Total time: 9.02 secs
 
------------ BDX END ----------------------------------------------------`

Text from the profiler has the same problem.

**Comment by GoranM** [comment]
To generate the bitmap font texture, and the accompanying data, the BDX exporter runs a program called Hiero, as can be seen [here](https://github.com/GoranM/bdx/blob/d591914fe4162c46105cf28acce5c8d269a96fe2/blender/bdx/exporter.py#L704-L730).

It's possible that the assumed lwjgl class paths (which are provided as part of the command,  via the -cp switch) don't match where the jars actually reside on the system. 

Someone with a mac would have to confirm that.

**Comment by songproducer** [comment]
I printed out the jars variable:

jars = ['/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.9.2/e641cb91bec06bc64d9ddf7a7d7062caceec73cd/gdx-1.9.2.jar', '/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/dde4cf7e9ce61c24042f512203aed87657496639/gdx-platform-1.9.2-natives-desktop.jar', '/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.9.2/d710a8704ed584ec2ba9ca52e3a6a5885dd759cc/gdx-backend-lwjgl-1.9.2.jar', '/Users/leotreasure/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.1/f58c5aabcef0e41718a564be9f8e412fff8db847/lwjgl-2.9.1.jar', '/Users/leotreasure/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.1/2d12c83fdfbc04ecabf02c7bc8cc54d034f0daac/lwjgl-platform-2.9.1-natives-osx.jar', '/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/gen/hiero/gdx-tools.jar']

gdx-tools.jar is there.

Also printed out the hiero variable:

hiero = java -cp "/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.9.2/e641cb91bec06bc64d9ddf7a7d7062caceec73cd/gdx-1.9.2.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/dde4cf7e9ce61c24042f512203aed87657496639/gdx-platform-1.9.2-natives-desktop.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.9.2/d710a8704ed584ec2ba9ca52e3a6a5885dd759cc/gdx-backend-lwjgl-1.9.2.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.1/f58c5aabcef0e41718a564be9f8e412fff8db847/lwjgl-2.9.1.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.1/2d12c83fdfbc04ecabf02c7bc8cc54d034f0daac/lwjgl-platform-2.9.1-natives-osx.jar:/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/gen/hiero/gdx-tools.jar" com.badlogic.gdx.tools.hiero.Hiero 

All those files appear to be there. How can I help to debug this?

**Comment by songproducer** [comment]
I printed out some more variables:

ver = test5
gdx_jars = [None, None, None]

Also I'm not sure what I've changed but the error has now changed to:

Exception: Font gen: Can't find required gdx jars

Full traceback:


Traceback (most recent call last):
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 884, in execute
    return export(context, self.filepath, self.scene_name, self.exprun, self.apply_modifier)
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 834, in export
    generate_bitmap_fonts(fonts, hiero_dir, fonts_dir, textures_dir);
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 727, in generate_bitmap_fonts
    (try running the game without any text objects first)")
Exception: Font gen: Can't find required gdx jars                 (try running the game without any text objects first)

location: /Users/leotreasure/ApplicationsH/blender.app/Contents/MacOS/../Resources/2.77/scripts/modules/bpy/ops.py:189

location: /Users/leotreasure/ApplicationsH/blender.app/Contents/MacOS/../Resources/2.77/scripts/modules/bpy/ops.py:189
Error: Traceback (most recent call last):
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 884, in execute
    return export(context, self.filepath, self.scene_name, self.exprun, self.apply_modifier)
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 834, in export
    generate_bitmap_fonts(fonts, hiero_dir, fonts_dir, textures_dir);
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 727, in generate_bitmap_fonts
    (try running the game without any text objects first)")
Exception: Font gen: Can't find required gdx jars                 (try running the game without any text objects first)

location: /Users/leotreasure/ApplicationsH/blender.app/Contents/MacOS/../Resources/2.77/scripts/modules/bpy/ops.py:189

Traceback (most recent call last):
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/exprun.py", line 57, in execute
    bpy.ops.export_scene.bdx(filepath=file_path, scene_name=scene.name, exprun=True)
  File "/Users/leotreasure/ApplicationsH/blender.app/Contents/MacOS/../Resources/2.77/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 884, in execute
    return export(context, self.filepath, self.scene_name, self.exprun, self.apply_modifier)
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 834, in export
    generate_bitmap_fonts(fonts, hiero_dir, fonts_dir, textures_dir);
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/exporter.py", line 727, in generate_bitmap_fonts
    (try running the game without any text objects first)")
Exception: Font gen: Can't find required gdx jars                 (try running the game without any text objects first)

location: /Users/leotreasure/ApplicationsH/blender.app/Contents/MacOS/../Resources/2.77/scripts/modules/bpy/ops.py:189



location: <unknown location>:-1

location: <unknown location>:-1

**Comment by songproducer** [comment]
Could this be the problem?
https://github.com/libgdx/libgdx/issues/3578

**Comment by GoranM** [comment]
> Also I'm not sure what I've changed but the error has now changed

Compare the files you changed with the files that are currently in master.

You need to return to the original state, where you get the original error. Create a completely new project if necessary.

> Could this be the problem?

It seems unlikely, since those changes are for the audio subsystem, and they've been integrated into the libgdx version that we currently use.

-

What happens when you run the command directly in the osx terminal?

```
java -cp "/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.9.2/e641cb91bec06bc64d9ddf7a7d7062caceec73cd/gdx-1.9.2.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/dde4cf7e9ce61c24042f512203aed87657496639/gdx-platform-1.9.2-natives-desktop.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.9.2/d710a8704ed584ec2ba9ca52e3a6a5885dd759cc/gdx-backend-lwjgl-1.9.2.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.1/f58c5aabcef0e41718a564be9f8e412fff8db847/lwjgl-2.9.1.jar:/Users/leotreasure/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.1/2d12c83fdfbc04ecabf02c7bc8cc54d034f0daac/lwjgl-platform-2.9.1-natives-osx.jar:/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/gen/hiero/gdx-tools.jar" com.badlogic.gdx.tools.hiero.Hiero
```

Do you get the same error?

**Comment by songproducer** [comment]
Running the java command returns the same error:

Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: Unable to extract LWJGL natives.
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:67)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.initialize(LwjglCanvas.java:76)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.<init>(LwjglCanvas.java:68)
	at com.badlogic.gdx.tools.hiero.Hiero.<init>(Hiero.java:175)
	at com.badlogic.gdx.tools.hiero.Hiero$19.run(Hiero.java:1553)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: liblwjgl.dylib
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:126)
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:148)
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:59)
	... 18 more

**Comment by GoranM** [comment]
I don't know.

You could try asking someone in the libgdx community.

**Comment by songproducer** [comment]
Fixed! Needed to remove ~/.gradle folder and redownload dependencies via "Export and Run" button. I guess I corrupted things changing Android SDK platforms and tools versions.

**Comment by GoranM** [comment]
Ah, good to know.
