### ISSUE TITLE
Can't create new project: El Capitan

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#752]
Tried to start uninstalling the addon and reinstalling, new project, got this:

Extension controllers found
Executing '/Users/leotreasure/bdx/test7/gradlew clean'
Configuration on demand is an incubating feature.
:android:clean UP-TO-DATE
:core:clean UP-TO-DATE
:desktop:clean UP-TO-DATE
:html:clean UP-TO-DATE
:ios:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2.538 secs
Traceback (most recent call last):
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 267, in execute
    self.set_android_sdk_version()
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 151, in set_android_sdk_version
    build_tools_version = get_version_dir_name(build_tools_dir, build_tools_sort_key, "20.0.0")
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 128, in get_version_dir_name
    return sorted(os.listdir(path), key=sort_key)[-1]
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 141, in build_tools_sort_key
    n += int(''.join(c for c in hto[i] if c.isdigit())) * 10 ** i
ValueError: invalid literal for int() with base 10: ''

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by rafcolson** [comment]
What is your build tools version? For example, mine is `23.0.1`.

**Comment by songproducer** [comment]
In Android Studio, it shows these are installed:
23.0.1
23.0.2
23.0.3

**Comment by rafcolson** [comment]
Linux or Mac?

**Comment by songproducer** [comment]
Mac

**Comment by rafcolson** [comment]
I'm guessing that on Mac `''` is interpreted differently. I'll change it to `""` and give you a build, to test if that would solve the issue.

**Comment by songproducer** [comment]
thanks very much!

**Comment by rafcolson** [comment]
Here's the [build](https://www.dropbox.com/sh/lag9ct4rntnee74/AAAp2f9RR3B-ccTAt8knUz9ca?dl=0).

**Comment by songproducer** [comment]
I got a more descriptive error this time:

Android SDK location '/Users/leotreasure/android-sdk/' doesn't contain an SDK
Executing '/Users/leotreasure/bdx/test6/gradlew clean'
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> failed to find target with hash string 'android-20' in: /Users/leotreasure/android-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.018 secs
build-tools: .DS_Store
Traceback (most recent call last):
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 268, in execute
    self.set_android_sdk_version()
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 152, in set_android_sdk_version
    build_tools_version = get_version_dir_name(build_tools_dir, build_tools_sort_key, "20.0.0")
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 128, in get_version_dir_name
    return sorted(os.listdir(path), key=sort_key)[-1]
  File "/Users/leotreasure/Library/Application Support/Blender/2.77/scripts/addons/bdx/ops/createproj.py", line 142, in build_tools_sort_key
    n += int("".join(c for c in hto[i] if c.isdigit())) * 10 ** i
ValueError: invalid literal for int() with base 10: ''

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by songproducer** [comment]
I just noticed something odd when I tried to launch the Android standalone SDK manager - there's no tools folder hence no android program to run.

**Comment by rafcolson** [comment]
Okay.

>`failed to find target with hash string 'android-20' in: /Users/leotreasure/android-sdk`

See the [Wiki's Installation page](https://github.com/GoranM/bdx/wiki/Installation#android).

>`build-tools: .DS_Store`

As expected there's a hidden file in the `build-tools` directory. Removing this should solve the issue.

I'll be working on a fix so any irrelevant folders in the `build-tools` directory will be ignored.

**Comment by songproducer** [comment]
Thanks! That did it!

**Comment by rafcolson** [comment]
No problem.

**Comment by rafcolson** [comment]
PR submitted. Any hidden folders won't cause this ValueError anymore.

**Comment by rafcolson** [comment]
PR merged. Thanks.
