### ISSUE TITLE
Bug: don't dispose of already disposed models in Bdx.dispose()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#760]
Tried `Bdx.dispose()` on Android, but it will crash the game when models over multiple scenes are shared.

Logcat showed this IllegalArgumentException:
```java
08-19 16:51:26.603 25609-25630/com.raco.test E/AndroidRuntime: FATAL EXCEPTION: GLThread 24377
                                                               Process: com.raco.test, PID: 25609
                                                               java.lang.IllegalArgumentException: buffer not allocated with newUnsafeByteBuffer or already disposed
                                                                   at com.badlogic.gdx.utils.BufferUtils.disposeUnsafeByteBuffer(BufferUtils.java:507)
                                                                   at com.badlogic.gdx.graphics.glutils.VertexBufferObject.dispose(VertexBufferObject.java:260)
                                                                   at com.badlogic.gdx.graphics.Mesh.dispose(Mesh.java:507)
                                                                   at com.badlogic.gdx.graphics.g3d.Model.dispose(Model.java:352)
                                                                   at com.nilunder.bdx.Scene.dispose(Scene.java:404)
                                                                   at com.nilunder.bdx.Scene.runObjectLogic(Scene.java:883)
                                                                   at com.nilunder.bdx.Scene.update(Scene.java:921)
                                                                   at com.nilunder.bdx.Bdx.main(Bdx.java:255)
                                                                   at com.raco.test.BdxApp.render(BdxApp.java:31)
                                                                   at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
                                                                   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
                                                                   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```
The same with `Scene.models` and `Bdx.spriteBatch`. On Desktop:
```java
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: buffer not allocated with newUnsafeByteBuffer or already disposed
        at com.badlogic.gdx.utils.BufferUtils.disposeUnsafeByteBuffer(BufferUtils.java:507)
        at com.badlogic.gdx.graphics.glutils.VertexArray.dispose(VertexArray.java:65)
        at com.badlogic.gdx.graphics.Mesh.dispose(Mesh.java:507)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.dispose(SpriteBatch.java:1010)
        at com.nilunder.bdx.Bdx.dispose(Bdx.java:413)
        at com.raco.test.BdxApp.dispose(BdxApp.java:26)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:243)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
This seems to be fixed by catching these three exceptions in `Bdx.dispose()` and `Scene.dispose()`.

Anyone knows if there are any alternative ways? We can't check if a model is already disposed, can we?

**Comment by SolarLune** [comment]
Set the references to `null` after disposing them; then you can check to see if they're not `null`. Similarly for a Collection, if you want to dispose of models or other resources, just take them out of the Collection after disposing of them.

**Comment by rafcolson** [comment]
Can't reproduce anymore so I'm closing this. Must have done something wrong.
