### ISSUE TITLE
Dev: building BDX using Ant

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#86]
Hi,

So I'm having some problems with building BDX using Ant.

I'm not getting any exceptions while building BDX and the build runs fine with the desktop build on Blender. However, when I build an *.apk with gradlew I'm getting an exception (displayed on the bottom of this post). I also get an exception when running dektop outside Blender.

I know for sure it hasn't anything to do with building for android, because this works fine with any of the official builds of BDX.

So my question is: how do you do it?

These are the steps I'm following:
1. download/unzip apache-ant-1.9.4
2. copy/paste ant.bat from the bin directory to the GitHub bdx folder
3. run ant.bat using cmd.exe
4. zip the GitHub bdx folder using 7-zip (normal compression).
5. install the add-on for Blender

Thanks for your help.

gradlew android:assembleDebug
```
Configuration on demand is an incubating feature.
:android:preBuild
:android:compileDebugNdk UP-TO-DATE
:android:preDebugBuild
:android:checkDebugManifest
:android:prepareDebugDependencies
:android:compileDebugAidl UP-TO-DATE
:android:compileDebugRenderscript UP-TO-DATE
:android:generateDebugBuildConfig UP-TO-DATE
:android:mergeDebugAssets UP-TO-DATE
:android:generateDebugResValues UP-TO-DATE
:android:generateDebugResources UP-TO-DATE
:android:mergeDebugResources UP-TO-DATE
:android:processDebugManifest UP-TO-DATE
:android:processDebugResources UP-TO-DATE
:android:generateDebugSources UP-TO-DATE
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:android:compileDebugJava UP-TO-DATE
:android:preDexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or versi
on (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:
472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:4
06)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary
(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.jav
a:251)
        at com.android.dx.command.dexer.Main.processClass(Main.java:704)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpen
er.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.j
ava:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java
:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/nilunder/bdx/Bdx$ArrayListScenes.class

1 error; aborting
:android:preDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:preDexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\Acer\AppData\Local\Android\sdk\build-tools\21.1.2\dx.bat --dex
--output D:\BLENDER\BDX\projects\Test\test\android\build\pre-dexed\debug\bdx-c5d
071fb780899f8af1909248515b24ed7c51d70.jar D:\BLENDER\BDX\projects\Test\test\core
\libs\bdx.jar
Error Code:
        1
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe)
or version (0034.0000)
                at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFi
le.java:472)
                at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFil
e.java:406)
                at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfN
ecessary(DirectClassFile.java:388)
                at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClass
File.java:251)
                at com.android.dx.command.dexer.Main.processClass(Main.java:704)

                at com.android.dx.command.dexer.Main.processFileBytes(Main.java:
673)
                at com.android.dx.command.dexer.Main.access$300(Main.java:83)
                at com.android.dx.command.dexer.Main$1.processFileBytes(Main.jav
a:602)
                at com.android.dx.cf.direct.ClassPathOpener.processArchive(Class
PathOpener.java:284)
                at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPath
Opener.java:166)
                at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpe
ner.java:144)
                at com.android.dx.command.dexer.Main.processOne(Main.java:632)
                at com.android.dx.command.dexer.Main.processAllFiles(Main.java:5
10)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)
        ...while parsing com/nilunder/bdx/Bdx$ArrayListScenes.class

        1 error; aborting


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 16.745 secs

D:\BLENDER\BDX\projects\Test\test>
```

gradlew desktop:run
```
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:desktop:processResources UP-TO-DATE
:desktop:classes
:desktop:run
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationExce
ption: Error parsing file: bdx/scenes/name.bdx
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
        at com.nilunder.bdx.Scene.init(Scene.java:119)
        at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:15)
        at com.raco.game.BdxApp.create(BdxApp.java:33)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:136)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:114)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: bdx\scene
s\name.bdx (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:164)
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
        ... 5 more

BUILD SUCCESSFUL

Total time: 15.699 secs
D:\BLENDER\BDX\projects\Test\test>
```

**Comment by SolarLune** [comment]
Not sure if you saw [this](https://github.com/GoranM/bdx/wiki/Building-BDX) page on the wiki, but you install Ant; it should set a variable that allows you to run it from the command-line just using "ant". That's how I do it, at least.

**Comment by rafcolson** [comment]
Well, my ```ANT_HOME```is set to ```C:\Program Files (x86)\Ant```, which contains all contents of this binary: [apache-ant-1.9.4-bin.zip](http://apache.cu.be//ant/binaries/apache-ant-1.9.4-bin.zip). And I'm running ant, starting in bdx repository.

But still Ant is not recognized. That's why I thought ant.batch had to be in my bdx folder.

What am I doing wrong?

**Comment by rafcolson** [comment]
I found the problem. I also hat to set a system variable ```PATH``` to ```%PATH%;%ANT_HOME%\bin```. Now it works!

Just in case anyone has the same problem, you can read more about installing Ant [here](http://ant.apache.org/manual/install.html#checkInstallation).
