### ISSUE TITLE
Profiler Issues

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#944]
I'm getting inconsistent results with the new profiler additions - I get the following error after deleting the profiler to re-export it:

```
Traceback (most recent call last):
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/ops/exprun.py", line 267, in execute
    export(self, context, bpy.context.scene.bdx.multi_blend_export, bpy.context.scene.bdx.diff_export)
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/ops/exprun.py", line 216, in export
    bpy.data.objects.remove(bpy.data.objects["__PBars"]);
KeyError: 'bpy_prop_collection[key]: key "__PBars" not found'
```

After that, I can export fine, but when I go to actually enable the profiler and run, I get this:

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.nilunder.bdx.utils.Profiler.init(Profiler.java:353)
	at com.nilunder.bdx.Scene.init(Scene.java:202)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:111)
	at com.solarlune.icontest.BdxApp.create(BdxApp.java:20)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

**Comment by SolarLune** [comment]
OK, that PR should resolve the first one - I think the second one was caused by me not deleting my previous BDXMono font file.

**Comment by rafcolson** [comment]
Perhaps it would be better to remove all data after all blend files are exported?

**Comment by SolarLune** [comment]
What do you mean?

**Comment by rafcolson** [comment]
What I meant was to remove all data of the profiler after all blend files are exported, because now the issue with the profiler remains with multi blends. I'll have a look. Also, sorry that I didn't check if that commit would also work with multi blends.

**Comment by SolarLune** [comment]
Yeah, the profiler data is removed after all the blend files are exported, it's that when multi-blend mode is on, Blender saves and reloads after export (as it appends the scenes from the other blend files in the directory into the exporting blend file). This means that the objects the profiler appends are also removed before that block at the bottom, which is what throws the error. The PR I submitted resolves this issue, though.

No problem.

**Comment by rafcolson** [comment]
Oh okay, I didn't know. I was just looking at the code. So there's no problem with the profiler with multi blends. That's good.

**Comment by SolarLune** [comment]
The PR was merged, so I think we're good. Thanks. Issue closed.
