### ISSUE TITLE
Bug: Getting  #iterator() cannot be used nested. Error when using a socketio client with bdx

### ISSUE THREAD

**Issue by christ182** [GoranM/bdx#986]
Hello, I'm having trouble spawning objects. I'm getting this error Exception in thread "EventThread" com.badlogic.gdx.utils.GdxRuntimeException: #iterator() cannot be used nested. 

Basically I get this error when I create a new game object inside a socketio listener.

Here's my stacktrace:

Exception in thread "EventThread" com.badlogic.gdx.utils.GdxRuntimeException: #iterator() cannot be used nested.
        at com.badlogic.gdx.utils.Array$ArrayIterator.hasNext(Array.java:541)
        at com.badlogic.gdx.graphics.g3d.Material.<init>(Material.java:68)
        at com.badlogic.gdx.graphics.g3d.Material.<init>(Material.java:62)
        at com.badlogic.gdx.graphics.g3d.Material.copy(Material.java:74)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.invalidate(ModelInstance.java:269)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.invalidate(ModelInstance.java:283)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.copyNodes(ModelInstance.java:226)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:154)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:146)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:62)
        at com.nilunder.bdx.gl.Mesh.getInstance(Mesh.java:244)
        at com.nilunder.bdx.GameObject.mesh(GameObject.java:775)
        at com.nilunder.bdx.Scene.cloneNoChildren(Scene.java:478)
        at com.nilunder.bdx.Scene.clone(Scene.java:537)
        at com.nilunder.bdx.Scene.add(Scene.java:586)
        at com.nilunder.bdx.Scene.add(Scene.java:611)
        at com.reins182.chess.Piece.<init>(Piece.java:34)
        at com.reins182.chess.Game.initPiece(Game.java:104)
        at com.reins182.chess.Game$2.call(Game.java:47)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Socket.onevent(Socket.java:338)
        at io.socket.client.Socket.onpacket(Socket.java:289)
        at io.socket.client.Socket.access$100(Socket.java:24)
        at io.socket.client.Socket$2$2.call(Socket.java:120)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Manager.ondecoded(Manager.java:427)
        at io.socket.client.Manager.access$1600(Manager.java:30)
        at io.socket.client.Manager$7.call(Manager.java:403)
        at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
        at io.socket.client.Manager.ondata(Manager.java:419)
        at io.socket.client.Manager.access$1000(Manager.java:30)
        at io.socket.client.Manager$2.call(Manager.java:370)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
        at io.socket.engineio.client.Socket$5.call(Socket.java:335)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
        at io.socket.engineio.client.transports.Polling.access$700(Polling.java:18)
        at io.socket.engineio.client.transports.Polling$2.call(Polling.java:127)
        at io.socket.engineio.parser.Parser.decodePayload(Parser.java:299)
        at io.socket.engineio.client.transports.Polling._onData(Polling.java:137)
        at io.socket.engineio.client.transports.Polling.onData(Polling.java:107)
        at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:127)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by SolarLune** [comment]
I'm gonna guess this is because you're trying to add things in another thread, essentially. I haven't done any work with sockets, though, so this is just a theory. Could you try creating an intermediary of some sort? Like, add the name of the object you want to create to a list in the socket listener, and then add the object by checking that list?

**Comment by christ182** [comment]
It worked! Thanks man

**Comment by SolarLune** [comment]
No prob! Glad to hear it worked.
